- src/cinder/app/AppImplMsw.cpp
In case of full screen the window always jumped to the first monitor even it was requested from another one.
> fix full screen in multiple monitors under windows

- include/cinder/Channel.h
Shared pointer typedefs are missing for Channel. They are also missing from all the other branches as well.
> fix missing shared pointer typedefs for channel

- include/cinder/app/App.h
- src/cinder/app/App.cpp
Instead of returning its own mMessage ivar (which was empty).
Fixes #648.
> AssetLoadExc uses setDescription()

- include/cinder/gl/TextureFont.h
- src/cinder/gl/TextureFont.cpp
Pass as `TextureFont::DrawOptions().glslProg( shader )`
Sample result:
Also includes the bugfixes from #644
> User can specify GlslProg for use when rendering TextureFont.

- src/cinder/gl/TextureFont.cpp
Fix infinite vao stack growth.
Correct per-glyph coloring when provided by user.
> TextureFont bugfixes

- src/cinder/Log.cpp
Two lines modification to address the “issue” explained here:
https://forum.libcinder.org/topic/using-the-new-log-feature-in-glnext#23
286000002245021
Thanks to std::ofstream::is_open, it is easy to check whether the file has already been created or not (http://www.cplusplus.com/reference/fstream/ofstream/is_open/).
> LoggerFile: Create the file only if/when needed.

- src/cinder/gl/Texture.cpp
Fixes issue #656.
std::swap would only work on (0.0, 1.0) y-texcoord inputs. Take (0.5, 1.0) for example. Swap would yield (1.0, 0.5) while the correct values are in fact (0.5, 0.0).
> Fixed texture's getAreaTexCoords on less than full size area inputs.

- docs/welcome/GitSetup.html
Fixes #489
Update the provided `git clone` commands and a few other small elements. There are several other things on this page that could use updating, but since this doc is linked off the main README, I thought the cloning bit at least should be accurate until a more substantial overhaul.
Other stuff that needs tweaking:
- Screenshots
- Git Installers
- VC Version Support
> Update git clone guidance in Git Setup Guide, fixes #489

- include/cinder/audio/Debug.h
- src/cinder/audio/msw/FileMediaFoundation.cpp
- test/_audio/VoiceTest/src/VoiceTestApp.cpp
Fixes issue [reported here](https://forum.libcinder.org/topic/cinder-audio-playing-files-of-different-formats-at-different-pitches#23286000002259009).
Also made the log placeholder macros more like those in 0.9.0.
> audio: SourcefileMediaFoundation clone fix

- include/cinder/Json.h
- src/cinder/Json.cpp
Fixes #667.
Also fixed a doc and a couple minor whitespace improvements.
Comments test in test/JsonTest is now passing.
> Add JsonTree::ParseOptions::allowComments(), enabled by default

- include/cinder/app/AppImplMswBasic.h
- src/cinder/app/AppImplMswBasic.cpp
When calling ```quit()```, the application's windows were not properly closed and destroyed, causing memory leak detectors to go nuts on application exit. To fix this, the ```quit()``` method now simply closes all open windows, forcing the application to quit as soon as the last window is closed.
I've implemented and tested this code only on Windows.
> Fix for memory leak when quitting.

- src/cinder/Color.cpp
Apparently this one has been left out when updating the Color class. There's the function signature for the 4 color types, but only the implementation for ColorA<uint8_t> and ColorA<float>.
This PR fixes this.
> Missing implementation of Color / "std::ostream& operator<<"

- include/cinder/svg/Svg.h
Enables use of findByIdContains() with nodes that were found using any of the svg::find* methods.
> Const-correctness for svg::findByIdContains.

- xcode/fullbuild.sh
Getting the full path of the cinder.xcodeproj so that it can be run from other directories, ex.
```bash
./xcode/fullbuild.sh
```
Also reducing the number of xcodebuild commands by using `-alltargets`.
> Improve fullbuild.sh script

- include/cinder/gl/GlslProg.h
- src/cinder/gl/GlslProg.cpp
Saves a couple keystrokes for users who store shaders as `std::string`, since they don't need the extra `c_str()` this way.
> Pass in string shaders to GlslProg as std::string

- include/cinder/Frustum.h
A small change for the purpose of extracting Frustum Planes.
- This enables easy access of the Planes contained in Frustum specifically for use with aspects of gl including but not necessarily limited to [gl_ClipDistance](https://www.opengl.org/sdk/docs/man/html/gl_ClipDistance.xhtml) functionality.
> Added getters for Frustum Planes

- include/cinder/app/AppBase.h
- include/cinder/app/Platform.h
- include/cinder/app/cocoa/PlatformCocoa.h
- include/cinder/app/msw/PlatformMsw.h
- include/cinder/app/winrt/PlatformWinRt.h
- src/cinder/app/Platform.cpp
- src/cinder/app/cocoa/PlatformCocoa.cpp
Fixes #727, mostly just implements the changes discussed there. Notes to consider:
* in order to ensure that the base asset path is always loaded when you call `getAssetDirectories()`, we need to make sure it is prepared from that call. This means it can't be const, as the virtual `prepareAssetLoading()` method can't be const (we'd also have to make a couple variables mutable).
* considering to add a `getAssetBaseDirectory()` as a cleaner alternative to `getAssetPath( "" )`, which would essentially be the same as `getAssetDirectories()[0]`
> Distinguish between asset directories and paths

- include/cinder/app/AppBase.h
- include/cinder/app/cocoa/AppImplMac.h
- src/cinder/app/cocoa/AppImplMac.mm
- test/windowTest/src/windowTestApp.cpp
Merging against app_refactor since app impls have moved in that, amongst other changes. This includes:
* @lithium-snepo's fix for coming back from borderless and the resize buttons being gone. Internally it appears we need to resize the window to make this work (I tried a number of other things as well) - probably a bug on apple's part, but seeing as how the window is already visually changing, doesn't have any real side effects.
* caching the window title so that we can restore it after coming back from borderless
* `App::Settings::setTitle()` also sets the default `Window::Format`'s title. This seems like expected behavior, and also I think this is how things already work on windows (on mac, you had to explicitly call `Window::setTitle()`)
Fixes issues in #694, supersedes #709
> mac borderless fixes

- src/cinder/Log.cpp
- test/DebugTest/src/DebugTestApp.cpp
Related to issue #717
* There may be a more appropriate way to get an error message to the user other than ```cerr```, but I didn't want to rely on any app contexts, etc.
* I hit the ```cerr``` when I call ```testEnableFile();``` and it gives an empty path, but not when I call ```testEnableBadFilePath();``` with a bogus path.  I'm a little confused about it, but not really worried.
> creates containing folder for logging

- include/cinder/audio/GenNode.h
- include/cinder/audio/NodeMath.h
- include/cinder/audio/Param.h
- src/cinder/audio/GenNode.cpp
- src/cinder/audio/Node.cpp
- src/cinder/audio/Param.cpp
- src/cinder/audio/SamplePlayerNode.cpp
Some minor-ish features and bug fixes that I've collected over the last few months, getting them back into master. Main changes are:
* improvements to the changes in #575, advanced audio timing with `audio::Param`.
* `audio::Param` handles time with double precision floating point now, to make the conversion to and from size_t sample to normalized time more accurate. Fixes #729
* added `GenNode::setPhase()`
* added shared_ptr `Ref` typedefs for `audio::MathNode` types
* you can attach labels to `audio::Event` for debugging purposes.
> audio updates

- samples/_opengl/MotionBlurVelocityBuffer/assets/motion-blur.fs
- samples/_opengl/MotionBlurVelocityBuffer/assets/neighbormax.fs
- samples/_opengl/MotionBlurVelocityBuffer/assets/passthrough.vs
- samples/_opengl/MotionBlurVelocityBuffer/assets/tilemax.fs
- samples/_opengl/MotionBlurVelocityBuffer/assets/velocity-render.fs
- samples/_opengl/MotionBlurVelocityBuffer/assets/velocity.fs
- samples/_opengl/MotionBlurVelocityBuffer/assets/velocity.vs
- samples/_opengl/MotionBlurVelocityBuffer/src/BlurrableThings.h
- samples/_opengl/MotionBlurVelocityBuffer/src/MotionBlurVelocityBufferApp.cpp
- samples/_opengl/MotionBlurVelocityBuffer/xcode/MotionBlurVelocityBuffer.xcodeproj/project.pbxproj
Use two FBOs with multiple attachments (one FBO for each size needed).
GPU and CPU frame timing added to params.
Separate methods for each phase of the blur process should be easier to follow.
Update shaders to 330 core so we can specify layout for FBO attachments.
> Blur sample update

- include/cinder/gl/Batch.h
- include/cinder/gl/Context.h
- include/cinder/gl/gl.h
- src/cinder/gl/Batch.cpp
- src/cinder/gl/Context.cpp
- src/cinder/gl/Vao.cpp
- src/cinder/gl/gl.cpp
Redesigning gl::Context VAO stack to use raw pointers instead of shared_ptr's. Small but measurable optimization.
> Moving gl::Context from VaoRef stack to Vao* stack

- include/cinder/gl/Texture.h
Simple change to add `setWrap( GLenum wrapS, GLenum wrapT, GLenum wrapR )` to `gl:: TextureBase` and `gl::Format` on non-ES GL.
> add setWrap varaint that includes depth

- include/cinder/gl/VboMesh.h
Allows you to use a MappedAttrib like:
```
mappedPosIter->y = updatedHeight;
```
instead of:
```
(*mappedPosIter).y = updatedHeight;
```
> Added VboMesh::MappedAttrib::operator->()

- include/cinder/Utilities.h
- src/cinder/Utilities.cpp
- xcode/cinder.xcodeproj/project.pbxproj
A very basic add of `getEnvironmentVariables()` to Utilities. Would it make sense to hoist this to `Platform` and `CocoaPlatform`?
As an aside, `CINDER_COCOA` is a little misleading since iOS does not have _Cocoa_ but instead _Cocoa Touch_ no? I'd almost rather `CINDER_OSX` and `CINDER_IOS` :wink:
> Allow access to environment variables on OS X and iOS

- src/cinder/gl/ShaderPreprocessor.cpp
Previous to the ShaderPreprocessor branch getting merged into glNext, one could have a version string that had leading spaces or tabs, which was quite handy if one defined their shader source in a C++11 multi-line raw string literal. Once merged, shader preprocessing is enabled by default and with the version check regex disallowed any space, it fails to find it and prepends *another* version string of the default value into the shader source, which causes the shader compile to fail.
The chage made here allows spaces and tabs to precede `#version` which avoids the double version string and compile issue. Only tested on OS X, though I would think other shader compilers would allow the whitespace as well, perhaps worth a quick test.
As a quick example, here is the passthrough vertex shader …
> Relax shader preprocessor version regex

- include/cinder/audio/Context.h
- test/_audio/NodeTest/src/NodeTestApp.cpp
enables syntax:
```
mGen = ctx->makeNode<audio::GenSineNode>( 440 );
```
Requires min visual studio version of 2013, so PR is against glNext (0.9.0).
> Context::makeNode() overload to construct NodeT with variadic template args

- include/cinder/gl/GlslProg.h
Would this be something interesting to add to the current GlslProg::Format implementation?
This is probably not going to be used a lot but I can definitely see this being useful in some specific cases.
Let me know what you think.
Cheers,
Simon.
> Added GlslProg::Format getters for the shader paths

- include/cinder/Breakpoint.h
- include/cinder/Log.h
- samples/_opengl/PostProcessingAA/src/fxaa/FXAA.cpp
- samples/_opengl/PostProcessingAA/src/smaa/SMAA.cpp
- src/cinder/Log.cpp
- test/DebugTest/src/DebugTestApp.cpp
- test/DebugTest/vc2013/DebugTest.vcxproj
- vc2013/cinder.vcxproj
- vc2013/cinder.vcxproj.filters
- vc2013_winrt/cinder.vcxproj
- vc2013_winrt/cinder.vcxproj.filters
- xcode/cinder.xcodeproj/project.pbxproj
- Added `LoggerBreakpoint`, a logger that doesn't print anything but instead triggers a breakpoint. You don't need to use it directly, instead you can write:
```
log::manager()->enableBreakOnError();
// or
log::manager()->enableBreakOnLevel( log::LEVEL_WARNING );
```
- Added `CI_BREAKPOINT()`, a cross-platform macro to trigger breakpoints at runtime. Resides in cinder/Breakpoint.h 
- Added a new macro called `CI_LOG_EXCEPTION`, which takes a user description ostream and the exception itself, and prints something informative like:
```
|error  | FXAA::FXAA()[38] exception caught loading fxaa.vert / frag, exception type: cinder::gl::GlslProgCompileExc, what: FRAGMENT: ERROR: 0:44: '.0' : syntax error: syntax error
```
I find that I almost exclusively log exceptions with this now in my …
> Gl next debug break

- include/cinder/audio/audio.h
- samples/_audio/BufferPlayer/src/BufferPlayerApp.cpp
- vc2013/cinder.vcxproj
- vc2013/cinder.vcxproj.filters
- vc2013_winrt/cinder.vcxproj
- vc2013_winrt/cinder.vcxproj.filters
- xcode/cinder.xcodeproj/project.pbxproj
closes #740 
Convenience header file that includes most of the `ci::audio` namespace.
> audio.h unbrella header

- include/cinder/Log.h
- src/cinder/Log.cpp
Removed default bool param, which was redundant. Removed default params for `setFileLoggingEnabled()` file-rolling variant, which was ambiguius on VC.
> log::manager interface improvments

- include/cinder/gl/scoped.h
- src/cinder/gl/scoped.cpp
this mirrors `gl::viewport( ivec2 )` ([here](https://github.com/cinder/Cinder/blob/glNext/include/cinder/gl/wrapper.h#L102))
> gl::ScopedViewport overload for ivec2 size

- include/cinder/Signals.h
- src/cinder/Signals.cpp
- test/SignalsTest/src/SignalsTest.cpp
- test/SignalsTest/xcode/SignalsTest.xcodeproj/project.pbxproj
boost::signals2 provided a shared_connection_block type that let users temporarily block calling of a given connection. This was pretty useful for pausing/unpausing type behavior.
This adds a `block`/`unblock` method pair to `ci::signals::Connection` that lets users temporarily suspend calling of a connected function.
> Signal Connections can be blocked/unblocked.

- include/cinder/MayaCamUI.h
- samples/Geometry/src/GeometryApp.cpp
- samples/_opengl/NormalMapping/src/NormalMappingApp.cpp
This is in order to add support for pan and zoom to touchpads such as mac laptops, which otherwise require the user to add custom mappings.
The `MayaCamUI::mouseDown( MouseEvent )` overload isn't particularly needed, I added it for symmetry.
> Add MayaCamUI overloads that take MouseEvent

- include/cinder/gl/GlslProg.h
- src/cinder/gl/GlslProg.cpp
This is a little cleaner way to add a private ShaderPreprocessor to GlslProg, as it is only initialized if preprocessing is enabled.
> Store GlslProg::mShaderPreprocessor as unique_ptr, forward declare

- src/cinder/app/cocoa/AppImplMac.mm
Resolves #584 (or at least works around it).
When a window's content view is directly assigned, an odd warning is spewed to the console about an unknown subview being added to `NSThemeFrame`, which is occurring in AppKit - this can be sidestepped by instead adding the CinderView as a subview of the window's content view.
> Avoid NSWindow warning on contentView assignment

- .gitignore
My local Cinder repo state is usually a bit polluted with statuses of a bunch of unknown non-core CinderBlocks and this tweak will ignore them. One catch is that if a new block were added or renamed, it would need to be reflected in the ignore file as well - initially I thought this was going to be a big deal, but it doesn't appear as though a block has been added in quite some time.
While I'm not sure others will find this as useful as I do, I thought I'd at least propose it.
> Ignore non-core CinderBlocks

- include/cinder/gl/Texture.h
- samples/_opengl/MipMap/src/MipMapApp.cpp
- src/cinder/gl/Texture.cpp
There's a few benefits to this rename that I see:
* reads a little clearer
* doesn't look funny 
* auto completes nicely
> rename Texture::getMaxMaxAnisotropy() -> getMaxAnisotropyMax()

- include/cinder/Sphere.h
- src/cinder/Sphere.cpp
Also make sure calculateBoundsSphere() doesn't crash when pased an empty array.
> init ivars in Sphere’s default constructor to zero

- include/cinder/app/cocoa/AppImplMac.h
Trivial tweak to resolve two warnings when building with Xcode 6.3.1 and the Cinder project has updated warning settings - both methods are already declared in above in the header.
> Remove duplicate quit and getContentScale method declarations

- include/cinder/gl/Context.h
- include/cinder/gl/scoped.h
- src/cinder/gl/Context.cpp
- src/cinder/gl/scoped.cpp
This PR adds a new RAII object for depth testing... see the discussion going [here](https://github.com/cinder/Cinder/issues/824).
> glNext gl::ScopedDepthBuffer

- src/cinder/Utilities.cpp
Only requires one Buffer object. Seems to have a near identical performance profile, but half the required memory consumption.
I'm using the iterator based string constructor, which provides the null terminator for us.
> improve loadString() implementation to only need one Buffer

- include/cinder/gl/Shader.h
- src/cinder/gl/EnvironmentCore.cpp
- src/cinder/gl/EnvironmentEs.cpp
- src/cinder/gl/Shader.cpp
Added support for simple directional diffuse lighting for stock shaders:
```auto shader = gl::getStockShader( gl::ShaderDef().lambert() );```
Can be combined with ```color()``` and ```texture()```, but by default will create a directional white light source at the camera's position.
> Added ci::gl::ShaderDef::lambert()

- src/cinder/System.cpp
The `Gestalt` functions have been deprecated since 10.8 (and are said to incorrectly report 10.10 as 10.9, though I was unable to reproduce on 10.10.3) and API was added to `NSProcessInfo` to replace it. Though the API wasn't made public until OS X 10.10 / iOS 8, it is available on earlier releases (possibly backported when using newer base SDKs due to `Gestalt` being deprecated without a replacement) so the Objective-C runtime is used to divine availability and execute, falling back to `Gestalt` with the deprecation warning hushed.
The `NSProcessInfo` API is also available on iOS and is a bit cleaner than the `-[UIDevice systemVersion]` string parsing, so it is use when available, falling back to the `UIDevice` method.
So far, I have only tested on 10.10.3 / Xcode 6.3 building the OS X …
> avoid deprecated Gestalt function to fetch OS X version when possible

- xcode/cinder.xcodeproj/project.pbxproj
While Xcode seemed to sort out how to properly handle this at compile-time, the frameworks were highlighted red in the file list indicating it couldn't find them which was a bit annoying. I suspect this is just a setting carried over from the original Xcode project file.
> Remove hardcoded QTKit and CoreVideo framework paths

- include/cinder/gl/scoped.h
- samples/Geometry/src/GeometryApp.cpp
- samples/StereoscopicRendering/src/StereoAutoFocuser.cpp
- samples/StereoscopicRendering/src/StereoscopicRenderingApp.cpp
- samples/_opengl/DeferredShading/src/DeferredShadingApp.cpp
- samples/_opengl/DeferredShadingAdvanced/src/DeferredShadingAdvancedApp.cpp
- samples/_opengl/MotionBlurVelocityBuffer/src/MotionBlurVelocityBufferApp.cpp
- samples/_opengl/StencilReflection/src/StencilReflectionApp.cpp
Resulting from the decisions made in #629, The three most common forms of blending are made explicit with `ScopedBlendAlpha`, `ScopedBlendPremult`, and `ScopedBlendAdditive`. Auto completion is a feature here. Updated samples that were making use of the previous versions.
For disabling blending altogether, you call (prexisting):
```cpp
ScopedBlend blend( false );
```
> made gl::ScopedBlend* more consistent

- include/cinder/Frustum.h
- src/cinder/Frustum.cpp
Sometimes you don't have a Camera to construct the Frustum from and in those cases you can't use cinder's Frustum class because you can currently only construct one from a Camera.
Let me know if you see something wrong, it's basically only a new constructor and the corresponding Frustum::set function. I also replaced some recurring code thanks to the new Frustum::set but it's all minor modifications.
> Added new Frustum constructor that doesn't need a Camera

- src/cinder/gl/ShaderPreprocessor.cpp
This is a partial fix for #850, where an extra "\n" was being added and was causing the error log's line number to be off by one.
> ShaderPreprocessor: remove extra line for user provided #version

- include/cinder/Signals.h
- test/SignalsTest/src/SignalsTest.cpp
- test/SignalsTest/xcode/SignalsTest.xcodeproj/project.pbxproj
Need to break out of the `mLinks` iteration too. Partly fixes issues with `params::InterfaceGl` + `CameraUi`
> signals: fix handled MouseEvents when they are coming from different priority groups

- include/cinder/gl/GlslProg.h
- include/cinder/gl/ShaderPreprocessor.h
- src/cinder/gl/GlslProg.cpp
- src/cinder/gl/ShaderPreprocessor.cpp
1) Adding custom search directory to `GlslProg::Format()` for includes
2) `GlslProg::getIncludedFiles()` returns a vector of `fs::path`s, handy for passing to a file watcher to live update the shader when an included file is modified.
> ShaderPreprocessor features

- src/cinder/app/msw/PlatformMsw.cpp
Adding localized resources on Windows is relatively easy: just add LANGUAGE LANG_GERMAN, SUBLANG_NEUTRAL to the Resources.rc file, and all resources following it will be listed as "German". Cinder did not support this out-of-the-box, so I've made a little change. This should have no effect on existing samples and applications.
Note: to support LANGUAGE tags, users must add '#include &lt;Windows.h&gt;' to their Resources.h file. Unfortunately, adding this line to 'cinder/CinderResources.h' does not seem to work, perhaps because the resource compiler doesn't properly handle includes-within-includes.
> Added support for LANGUAGE tags to Cinder's loadResource() method.

- src/cinder/gl/ShaderPreprocessor.cpp
fixes #909 
Adding the newline all the time would change the line numbers regardless of if the preprocessor was actually changing the shader source and without a newline, defines will append to the version line like:
```glsl
#version 150#define VARIABLE
…
```
> Add newline after user-provided shader version when using defines

- include/cinder/ip/Threshold.h
- src/cinder/ip/Threshold.cpp
- test/ThresholdTest/src/ThresholdTestApp.cpp
Removes `ip::AdaptiveThresholdT`'s internal `shared_ptr<Obj>`, which is the last of its kind. Updated / added test code to test/ThresholdTest. Trying to adhere to current best practices for memory management / const correctness.
Closes #763.
> AdaptiveThresholdT updates

- include/cinder/Rand.h
- samples/Earthquake/src/Earth.cpp
- samples/HodginParticlesRedux/src/Emitter.cpp
- samples/HodginParticlesRedux/src/ParticleController.cpp
- samples/_opengl/MotionBlurVelocityBuffer/src/MotionBlurVelocityBufferApp.cpp
- samples/_opengl/ParticleSphereCPU/src/ParticleSphereCPUApp.cpp
- samples/_opengl/ParticleSphereGPU/src/ParticleSphereGPUApp.cpp
- samples/_opengl/ShadowMapping/src/ShadowMappingApp.cpp
- samples/_opengl/TransformFeedbackSmokeParticles/src/TransformFeedbackSmokeParticlesApp.cpp
- samples/_timeline/TextInputTween/src/TextInputTweenApp.cpp
- samples/rayMarcher/src/RayMarcher.cpp
- samples/shadowMap/main.cpp
- samples/slerpBasic/src/slerpBasicApp.cpp
- test/_opengl/ConvenienceDrawingMethods/src/ConvenienceDrawingMethodsApp.cpp
- test/_opengl/QueryTest/src/QueryTestApp.cpp
- tour/Section 1/Chapter 1/src/Particle.cpp
- tour/Section 1/Chapter 2/src/Particle.cpp
- tour/Section 1/Chapter 3/src/Particle.cpp
- tour/Section 1/Chapter 4/src/ParticleController.cpp
- tour/Section 1/Chapter 5/src/ParticleController.cpp
- tour/Section 2/Chapter 1/src/ParticleController.cpp
- tour/Section 2/Chapter 2/src/ParticleController.cpp
- tour/Section 2/Chapter 3/src/ParticleController.cpp
- tour/Section 2/Chapter 4/src/ParticleController.cpp
- tour/Section 2/Chapter 5/src/ParticleController.cpp
Since moving to GLM, we've been removing the 'f' suffix for float types, as it is the default. This does the same for the Rand variants returning vec2 and vec3 types.
closes #705
> Removed f suffix from Rand::randVec2f and randVec3f

- src/cinder/gl/GlslProg.cpp
Now the exception error log from the ill-parsed index is:
```
|error  | const GlslProg::Uniform *cinder::gl::GlslProg::findUniform(const std::string &, int *) const[1007] Failed to parse index for uniform named: uColors[a], exception type: std::invalid_argument, what: stoi: no conversion
```
> GlslProg.cpp formatting and exception improvements

- include/cinder/app/cocoa/AppImplMac.h
- include/cinder/app/cocoa/AppMac.h
- src/cinder/app/cocoa/AppCocoaView.mm
- src/cinder/app/cocoa/AppImplMac.mm
- src/cinder/app/cocoa/AppMac.cpp
- xcode/cinder.xcodeproj/project.pbxproj
`UpdateSystemActivity()` is deprecated as of OS X 10.8 and the recommended IOKit replacement `IOPMAssertionCreateWithName ` works on Mac OS X 10.6 and later.
Separate power management assertions are required to prevent idle system sleep and idle display sleep and as such this complicates the `isPowerManagementEnabled` situation - to prevent leaking power management assertions look to see if both are valid and report that, this should allow power management to be disabled and attempt to re-enable while the opposite situation would leak an assertion (though they get cleaned up at app quit time). 
Power assertions can be checked via:
```sh
$ pmset -g assertions
```
**NOTE**: OS X applications will need to link to _IOKit.framework_
> Replace deprecated OS X power management API use

- include/cinder/app/Window.h
- samples/iosKeyboard/src/iosKeyboardApp.cpp
- samples/iosNativeControls/src/NativeControlsApp.mm
- samples/iosNativeControls/xcode_ios/NativeControls.xcodeproj/project.pbxproj
For iosKeyboard and iosNativeControls. The latter solution is not so elegant, the NativeViewController point had to be made global but I don't yet see any problem with that in a real world scenario.
There's something I'd like to verify with other obj-c gurus (pinging @pizthewiz), in that I had to declare the Window's UIViewController as `__unsafe_unretained` because it was causing the sample's NativeViewController object to be deallocated when the Window::Format went out of scope (the sample is using ARC, while cinder is still retain / release).  I believe this is kosher, that you can use `__unsafe_unretained` from within a non-ARC project, but it would be nice if someone else could verify as it is a bit hard to find docs related to this.
> iOS sample fixes for latest glNext, post app_refactor

- src/cinder/app/cocoa/RendererImpl2dMacQuartz.mm
Otherwise I get:
```
/cinder/app/cocoa/RendererImpl2dMacQuartz.mm:92:9: error: no viable conversion from 'NSRect' (aka '_NSRect') to 'CGRect'
CGRect boundsRect = [[view superview] bounds];
^            ~~~~~~~~~~~~~~~~~~~~~~~~~
/System/Library/Frameworks/CoreGraphics.framework/Headers/CGGeometry.h:41:8: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'NSRect' (aka '_NSRect') to 'const CGRect &' for 1st argument
struct CGRect {
^
/System/Library/Frameworks/CoreGraphics.framework/Headers/CGGeometry.h:41:8: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'NSRect' (aka '_NSRect') to 'CGRect &&' for 1st argument
struct CGRect {
^
1 error generated.
```
> Fixing CGRect/NSRect 32-bit only compile error

- include/cinder/audio/Voice.h
- src/cinder/audio/Voice.cpp
This function adds the ability to clear the audio buffer cache that the MixerImpl retains.
I am aware of audio::Voice::Options().maxFramesForBufferPlayback to avoid buffering all together, but for my current application I load scenes with dozens of audio files that get played multiple times, so I want them to be cached, but I also want to be able to clear the cache once I unload that scene and load a new scene. This commit adds the ability to do this.
> Added static void Voice::clearBufferCache()

- samples/_opengl/ObjLoader/src/ObjLoaderApp.cpp
- src/cinder/ObjLoader.cpp
As reported [here](https://forum.libcinder.org/topic/missing-vertices-in-obj-output-glnext), positions weren't being written in by the `objWrite()` method, this added `geom::POSITION` to loaded requestedAttribs so that it does.
As an aside, I'd like to suggest this method be renamed to `writeObj()`, which is in alignment with methods like `writeImage()` or `writeFile()`, also it would make it an action thus more readable.
> write positions to obj file

- xcode/fullbuild.sh
Fixes #825
The `cinder_iphone_sim` target seems to build defaulting to the `iphone` SDK when built via `fullbuild.sh`, yielding bad simulator binaries. The tweak here just specifies the SDK for both the `cinder_iphone` and `cinder_iphone_sim` targets to make sure they build as expected - it is still possible to get oneself into trouble building these targets from Xcode with an unintended device vs simulator selection.
> Build iOS simulator target with simulator SDK to avoid bad archs

- include/cinder/ObjLoader.h
- samples/_opengl/ObjLoader/src/ObjLoaderApp.cpp
- src/cinder/ObjLoader.cpp
To be more consistent with other `write*` calls.
> rename objWrite() -> writeObj()

- include/cinder/ObjLoader.h
- samples/_opengl/ObjLoader/src/ObjLoaderApp.cpp
- src/cinder/ObjLoader.cpp
I added the option to not optimize vertices in ``ObjLoader``.
Instead of using a separate function, like it was in 0.8.6, I'm forcing the existing variable ``forceUnique`` to ``true`` for every vertex, when the user chooses to not optimize.
It's a pretty minimal change, although it might not be the fastest way, not sure.
I also fixed a namespace bug in the ObjLoader sample.
> Add no optimization option to Objloader

- xcode/cinder.xcodeproj/project.pbxproj
So they are still visible within xcode, but don't compile into anything there.
> adding un-targeted files to Xcode project file

- src/cinder/gl/GlslProg.cpp
…where ```uUniformName[0].member``` is not supported because it only compares the name before the bracket.
See #948
> Addressing GlslProg uniform issue with array of struct member access

- include/cinder/GeomIo.h
- include/cinder/gl/draw.h
- samples/Geometry/assets/phong_es2.frag
- samples/Geometry/src/GeometryApp.cpp
- src/cinder/GeomIo.cpp
- src/cinder/gl/draw.cpp
In response to https://forum.libcinder.org/#Topic/23286000002349013 , I have created a version of ```drawStrokedCircle``` that supports an arbitrary line width. It creates a triangle strip instead of a line loop. 
I should not have to mention that for line width values smaller than 1.0, you need proper (msaa) sub-sampling to make it look good.
> Added a drawStrokedCircle that supports a lineWidth setting.

- include/cinder/gl/Texture.h
- src/cinder/gl/Texture.cpp
- src/cinder/gl/draw.cpp
- src/cinder/qtime/QuickTimeGlImplAvf.cpp
- test/_opengl/TextureUpload/xcode/TextureUpload.xcodeproj/project.pbxproj
This address 2 issues; the first is my approach for #542, adding an optional custom deleter to the Format of the various Texture types. Second, this makes "clean bounds" on Texture2d the default mode of thinking, and the 'actual' size specialized. For the average use case none of this matters, but it makes having a clean bounds distinct from the full Texture2d behave more naturally in more situations.
> Adds deleter to Texture*::Format; changes clean bounds semantics

- include/cinder/app/TouchEvent.h
- samples/MultiTouchBasic/src/MultiTouchBasicApp.cpp
By defining the operators within the cinder::app namespace. Fixes #915.
> Fix appTouchEvent operator<<

- include/cinder/app/AppBase.h
- include/cinder/app/AppScreenSaver.h
- include/cinder/app/Platform.h
- include/cinder/app/cocoa/AppCocoaTouch.h
- include/cinder/app/cocoa/AppCocoaView.h
- include/cinder/app/cocoa/AppMac.h
- include/cinder/app/cocoa/PlatformCocoa.h
- include/cinder/app/msw/AppImplMsw.h
- include/cinder/app/msw/AppImplMswBasic.h
- include/cinder/app/msw/AppMsw.h
- include/cinder/app/msw/PlatformMsw.h
- include/cinder/app/winrt/AppWinRt.h
- include/cinder/app/winrt/PlatformWinRt.h
- src/cinder/app/AppScreenSaver.cpp
- src/cinder/app/Platform.cpp
- src/cinder/app/cocoa/AppCocoaTouch.cpp
- src/cinder/app/cocoa/AppCocoaView.mm
- src/cinder/app/cocoa/AppMac.cpp
- src/cinder/app/cocoa/PlatformCocoa.cpp
- src/cinder/app/msw/AppImplMsw.cpp
- src/cinder/app/msw/AppMsw.cpp
- src/cinder/app/msw/PlatformMsw.cpp
- src/cinder/app/winrt/AppWinRt.cpp
- src/cinder/app/winrt/PlatformWinRt.cpp
- test/AppCocoaViewTest/AppCocoaViewTest.xcodeproj/project.pbxproj
- test/AppTest/src/AppTestApp.cpp
- test/AppTest/xcode/AppTest.xcodeproj/project.pbxproj
- test/ScreenSaverTest/xcode/ScreenSaverTest.xcodeproj/project.pbxproj
- test/iosAppTest/src/iosAppTestApp.cpp
This is done by adding an abstract virtual `Platform::getDefaultExecutablePath()`, which returns the best it can for the executable path on each platform. If a specific app needs to override this, they can by calling `Platform::setExecutablePath()`.  This makes it possible to, say, load a config file in your assets directory from the prepare settings function.
The previous abstract virtual `AppBase::getAppPath()` is no longer virtual, instead it routes to `Platform::getExecutablePath()`.
Also made `Platform::getHomeDirectory()` and `getDocumentsDirectory()` const. Tested on Mac, iOS, Win Desktop, Win32, and screensaver variants.
> Make app::loadAsset() work before App is instantiated

- include/cinder/app/Renderer.h
- include/cinder/app/RendererGl.h
- include/cinder/app/cocoa/AppCocoaTouch.h
- include/cinder/app/cocoa/AppCocoaView.h
- include/cinder/gl/Texture.h
- src/cinder/gl/VaoImplEs.cpp
Xcode 7 beta 1 warns on functions missing an explicit override specifier. Compilation tested on all 3 targets with Xcode 6.3.2 and Xcode 7 beta 1 on OS X 10.11.
> Use override specificer to quiet warnings

- include/cinder/audio/msw/FileMediaFoundation.h
- include/cinder/msw/CinderMsw.h
With this you can declare your COM member variables like:
```cpp
ci::msw::ManagedComPtr<::IMFSourceReader>  mSourceReader;
```
> ManagedComPtr, improvements for using ci::msw::makeComUnique()

- src/cinder/gl/GlslProg.cpp
- test/_opengl/GlslProgAttribTest/assets/UniformTest.frag
- test/_opengl/GlslProgAttribTest/src/GlslProgAttribTestApp.cpp
- test/_opengl/GlslProgAttribTest/xcode/GlslProgAttribTest.xcodeproj/project.pbxproj
I ran into a few issues with the existing `GlslProg::findUniform()` implementation, this is a redux that aims to fix those problems:
* Avoids exc_bad_access on the result uniform when the requested name has a left square bracket, but a match isn't found in `mUniforms` (bad access was on the `*resultLocation = ret->mLoc + stoi( ... )` line.
* Handles the case when an array uniform is requested, but a location offset isn't necessary because we found an exact match in mUniforms
* Handles bad struct member names, ex. "uTestStruct[2].blah" in the test app.
* Overall, tried to document and make the string matching logic easier to follow / more robust.
This has been tested on Mac only so far, MSW testing still needed.  Some suggestions / discussion around possible future improvements:
* Much of …
> GlslProg::findUniform() v3

- src/cinder/app/msw/RendererImplGlMsw.cpp
In 0.9.0, color buffer has no alpha channel because the **WGL_ALPHA_BITS_ARB** attribute has been removed probably for 10bpc support.
I think **WGL_ALPHA_BITS_ARB** should be set to 8 at 8bpc to create an alpha buffer.
> Alpha channel support at 8bpc on MSW

- src/cinder/GeomIo.cpp
Looks like my default radius was a bit insane, larger than the shape itself. This should fix #958.
> Fixed the default radius, was too big

- include/cinder/Display.h
- include/cinder/app/cocoa/PlatformCocoa.h
- src/cinder/app/cocoa/PlatformCocoa.cpp
- src/cinder/app/msw/PlatformMsw.cpp
- test/windowTest/src/windowTestApp.cpp
Propose adding a method to fetch the display name:
```C++
//! Returns the display's name or an empty string if unavailable.
std::string		getName() const { return mName; }
```
Now that Cinder links to the IOKit framework on the OS X side, we can fetch and expose the display name without any additional dependencies. Implementation tested on:
:heavy_check_mark: OS X 10.10.4 / Xcode 6.4 / `x86_64`
:heavy_check_mark: OS X 10.8.5 / Xcode 5.1.1 / `x86_64` & `i386` (both in a VM)
and verified by adding the following to `setup()` and checking the output:
```C++
for( auto &display : Display::getDisplays() ) {
console() << display->getName() << std::endl;
}
```
It is worth noting that an "AirPlay Display", the additional display made available by an extended desktop to an Apple TV, does not provide …
> Expose display name

- include/cinder/app/msw/PlatformMsw.h
- src/cinder/app/cocoa/PlatformCocoa.cpp
- src/cinder/app/msw/PlatformMsw.cpp
Accidentally missed in #967, the display name should be fetched from the underlying platform on the first `Display::getName()` access, not on display creation.
> Lazy fetch MSW display name

- include/cinder/Log.h
- src/cinder/Log.cpp
as EventLog API doesn't appear to be available there. This just gets the project building again, while LoggerSystem::write() will do nothing for now. @lucasvickers Can you think of a solution we can use on that platform?  I haven't spent too much time looking, but I did see a [suggestion here](https://social.msdn.microsoft.com/Forums/windowsapps/en-US/73c7fb3a-2183-4d60-b2b1-ff4aa9286700/systemdiagnosticseventlog-replacement) to use COM and EventWrite(), not sure what the difference is between that method and the one we're using.
> disabling LoggerSystem on winrt.

- src/cinder/CameraUi.cpp
Issue #879:
I updated the tumbling operation to take the camera's worldUp value, rather than always glm::vec3{0,1,0).
This allows for the tumble functionality to remain consistent after setWorldUp() is called, changing a camera's worldUp -- WorldUp can now be switched to change between Y-up, or Z-up, & the mouse controls do not invert.
> CameraUi Tumble Orientation

- include/cinder/gl/Texture.h
- src/cinder/gl/Texture.cpp
- src/cinder/gl/TextureFormatParsers.cpp
This PR adds a CubeMap::createFromDds() and createFromKTx() method, along with the matching infrastructure in gl::TextureData and the relevant file parsers.
DDS in particular is much too deep for us to support completely at the current moment. However I've attempted to address the basic uncompressed cases with this PR, along with some of the compressed cases. We'll add support as users require in practice.
Relevant to #858.
> CubeMaps from DDS and KTX

- include/cinder/app/AppBase.h
- src/cinder/app/AppBase.cpp
As proposed [here](https://forum.libcinder.org/topic/rfc-minor-changing-app-isprimarythread-to-ismainthread).
Also added a freestanding method so you can use `app::isMainThread()` instead, and some minor tab realignments that probably got unaligned after switching to glm.
> rename AppBase::isPrimaryThread() -> AppBase::isMainThread()

- include/cinder/ChanTraits.h
- include/cinder/CinderMath.h
- include/cinder/ImageFileTinyExr.h
- include/cinder/ImageIo.h
- include/cinder/Surface.h
- include/tinyexr/tinyexr.h
- samples/ImageFileBasic/src/ImageFileBasicApp.cpp
- samples/_opengl/HighDynamicRange/src/HighDynamicRangeApp.cpp
- src/cinder/CinderMath.cpp
- src/cinder/ImageFileTinyExr.cpp
- src/cinder/ImageIo.cpp
- src/cinder/Surface.cpp
- src/cinder/app/cocoa/PlatformCocoa.cpp
- src/cinder/app/msw/PlatformMsw.cpp
- src/cinder/app/winrt/PlatformWinRt.cpp
- src/cinder/gl/Texture.cpp
- src/tinyexr/tinyexr.cc
- vc2013/cinder.vcxproj
- vc2013/cinder.vcxproj.filters
- vc2013_winrt/cinder.vcxproj
- vc2013_winrt/cinder.vcxproj.filters
- xcode/cinder.xcodeproj/project.pbxproj
This PR represents a first pass at integrating EXR parsing via TinyEXR, and related changes to the ImageIo infrastructure (and gl::Texture) to support half / fp16.
There are a number of limitations here as this is a first pass. One is that we're limited to the compression types TinyEXR supports, which is ZIP (not ZIPS) and None. Additionally, for writing we only support FP32. However this does formalize an HDR file format with reasonable compression that all Cinder platforms can parse. As a note, we are not supporting Surface16f or similar, but we do have the infrastructure for converting fp16 ImageSources into the other types (uint8, uint16 and float32).
> OpenEXR + FP16 support in ImageIo

- include/cinder/gl/Fbo.h
- include/cinder/gl/draw.h
- include/cinder/ip/Flip.h
- samples/_opengl/DynamicCubeMapping/src/DynamicCubeMappingApp.cpp
- samples/_opengl/TransformFeedbackSmokeParticles/assets/renderSmoke.vert
- samples/_opengl/TransformFeedbackSmokeParticles/src/TransformFeedbackSmokeParticlesApp.cpp
- src/cinder/gl/Fbo.cpp
- src/cinder/gl/Texture.cpp
- src/cinder/gl/draw.cpp
- src/cinder/ip/Flip.cpp
This PR adds a few routines useful for debugging CubeMaps:
```
void drawEquirectangular( const gl::TextureCubeMapRef &texture, const Rectf &r );
void drawHorizontalCross( const gl::TextureCubeMapRef &texture, const Rectf &r );
void drawVerticalCross( const gl::TextureCubeMapRef &texture, const Rectf &r );
```
The DynamicCubeMapping sample now exercises these:
These all also take optional parameter to specify a level-of-detail (mip-level) to draw. Additionally, this PR adds a ip::flipHorizontal() method, fixes our vertical cross cubeMap importing to match CMFT, and addresses an issue with cubeMaps parsed from DDS / KTX not enabling mipmapping correctly.
> Debug drawing cubemaps

- xcode/cinder.xcodeproj/project.pbxproj
iOS project builds are broken due to these files not being in the iOS compile targets. There's also an issue with boost::filesystem not linking in the x86_64 simulator. I'm looking into that.
> Add TinyEXR source files to iOS compile step

- include/cinder/PolyLine.h
- src/cinder/PolyLine.cpp
Makes it easier switch between from clockwise to counter-clockwise winding order.
Returning a copy makes for a nicer API:
```c++
intersection = PolyLine2f::calcIntersection( shapeA, shapeB );
if (intersection.size()) {
// Reverse the winding order:
PolyLine2f outline = intersection.front().reverse();
// Use the outline
}
```
> Add PolyLine reverse() and reversed()

- samples/EaseGallery/src/EaseGalleryApp.cpp
- samples/PolygonBoolean/src/PolygonBooleanApp.cpp
- samples/bezierPath/src/bezierPathApp.cpp
- src/cinder/gl/Context.cpp
This PR enables unpremultiplied alpha blending as the default in GL. This seems to be the most convenient in general, and prevents some confusion common for beginners.
> Enabling alpha blending by default

- include/cinder/gl/BufferObj.h
- samples/Earthquake/src/Earth.cpp
- samples/_opengl/ClothSimulation/src/ClothSimulationApp.cpp
- samples/_opengl/DeferredShadingAdvanced/src/DeferredShadingAdvancedApp.cpp
- samples/_opengl/InstancedTeapots/src/InstancedTeapotsApp.cpp
- samples/_opengl/ParticleSphereCPU/src/ParticleSphereCPUApp.cpp
- src/cinder/gl/BufferObj.cpp
- src/cinder/gl/VboMesh.cpp
This modifies BufferObj::mapWriteOnly() to no longer take a boolean for 'invalidatePrevious'. Instead, an alternative method BufferObj::mapReplace() serves this role. This has been a common source of confusion even for experienced users.
> BufferObj::mapWriteOnly() changes

- include/cinder/gl/Batch.h
- src/cinder/gl/Batch.cpp
This change should break no existing API's, but allows gl::VertBatch to serve as a geom::Source. Useful for instantiating a gl::Batch( vertBatch ) in particular.
> Updating gl::VertBatch to derive from geom::Source & documentation; adds texCoord1

- include/cinder/Frustum.h
- src/cinder/Frustum.cpp
Any kind of matrix is supported, making it easier to construct a frustum in object or view space. The other constructors always create a world space frustum, so supply a view-projection matrix if you want to stay compatible.
> Added a Frustum constructor and set() method that takes a matrix. 

- include/cinder/Frustum.h
- src/cinder/Frustum.cpp
and added typedef for Frustum that uses float as type, like we've done with other classes such as `PolyLineT` in this release cycle.
> rename Frustum -> FrustumT

- include/cinder/Timeline.h
Because including `cinder/Timeline.h` in isolation causes a compile error on VS2013: 'max' : is not a member of 'std'.
> Added missing algorithm include for std::max.

- samples/_opengl/ShadowMapping/assets/shadow_mapping.frag
The problem became visible when "Render only shadow map" was toggled.
> Prevent below one alpha on shadowmapping fragment color.

- include/cinder/qtime/MovieWriter.h
- src/cinder/qtime/MovieWriter.cpp
To address issue brought up [here](https://forum.libcinder.org/#Topic/23286000002439001). This gets MovieWriter building on windows, although I was seeing an exception thrown when trying to open the file for writing, didn't have time to lookinto that yet.
> MovieWriter msw compile fixes

- include/cinder/TriMesh.h
Xcode 7 squawks that `clone` overrides a member function but is without the override keyword.
> Add missing override keyword to TriMesh::clone()

- src/cinder/app/cocoa/AppImplMac.mm
- test/AppTest/src/AppTestApp.cpp
As it turns out, it was indeed repro'able from keyDown(). I've also added test code to AppTest to iterate through a few common framerate settings, and they are working as expected now on mac.
Fixes #1088.
> Fix for AppMac::setFrameRate() crash

- samples/_opengl/PostProcessingAA/src/PostProcessingAAApp.cpp
I had completely missed this: https://github.com/cinder/Cinder/pull/1030 and lost way to much time trying to use SMAA in my app.
In the sample, SMAA only worked correctly because disableAlphaBlending() was called at the end of draw(), after the text information is drawn.
> Disable default alpha blending for smaa.

- src/cinder/GeomIo.cpp
The UV-coordinates for the ```Icosphere``` were calculated incorrectly and did not match those of the ```Sphere```.
> This should fix issue #1083. 

- include/cinder/gl/Fbo.h
I added this after stepping `Fbo::Format`'s constructor to find out what the defaults were. Now I know why `Fbo::getDepthTexture()` returns null with a default format. :)
Please feel free to suggest improvements to the doc, I'd be happy to modify it to improve understanding.
> Added doxygen doc for Fbo::Format, so users know what the defaults are.

- include/cinder/Frustum.h
- include/cinder/Plane.h
- src/cinder/Plane.cpp
Similar to what we've done for Frustum, Polyline, and others. I also added a couple lines of docs and modernized the exception subclass.
> rename PlaneT -> Plane, allows for typedef'ed Plane

- samples/_opengl/ObjLoader/assets/shader.frag
- samples/_opengl/ObjLoader/assets/shader_es2.frag
There's a small issue with this sample shaders.
Right before outputing the color, the whole RGBA is multiplied by the variable ```diffuse``` making the mesh transparent in some places. This creates some transparency issues as shown here:
Here's a corrected version. See how the two compares side by side:
> ObjLoader sample has some alpha issues

- include/cinder/Log.h
- src/cinder/Log.cpp
This allows you to do things like:
```cpp
log::manager()->getLogger<LoggerConsole>()->setTimestampEnabled();
CI_LOG_I( "blah" );
log::manager()->getLogger<LoggerConsole>()->setTimestampEnabled( false );
```
> Added LogManager::getLogger<T>, make LoggerMulti public

- src/cinder/audio/cocoa/FileCoreAudio.cpp
- src/cinder/qtime/AvfUtils.mm
- src/cinder/qtime/QuickTimeImplAvf.mm
I was trying to check out the clang address sanitizer in Xcode 7 and instead ended up running the static analysis tool which flagged these. It doesn't appear as though these are called through the update cycle or anything so I don't think they'd represent significant leaks or fixes - regardless they'd probably benefit from some quick validation.
> Plug a couple of OS X / iOS leaks

- src/cinder/app/cocoa/PlatformCocoa.cpp
- test/AppCocoaViewTest/src/MyCinderApp.cpp
- test/AppCocoaViewTest/src/MyCinderApp.h
Fixes #1074
It seemed as though the display finding functions directly accesses the `mDisplays` member variable which hasn't been lazy loaded when using `CinderViewMac`. Worth noting that the app runs into a context error (#1035) on OS X 10.11 unless the `#define USE_RENDERER2D` is removed from `MyCinderApp.h`
> Avoid direct/uninitialized display access on OS X / iOS

- include/cinder/gl/Texture.h
- src/cinder/gl/Texture.cpp
- test/_opengl/TextureUpload/vc2013/Resources.rc
- test/_opengl/usampler2D/src/usampler2DApp.cpp
- test/_opengl/usampler2D/xcode/usampler2D.xcodeproj/project.pbxproj
This should address #1099. It modifies the gl::Texture constructor that accepts an ImageSourceRef so that it automatically infers the dataType from the internalFormat. This most obviously manifests when attempting to create an integer texture.
> Inferring GL Texture dataType from internalFormat

- include/cinder/app/Platform.h
- src/cinder/app/Platform.cpp
So now the default assets path is searched and added right after Platform is constructed. Platforms where this is wasteful file access, such as android, can override `findAndAddDefaultAssetPath()` to disable this functionality.
> make Platform::getAssetPath() / loadAsset() const / thread-safe by removing lazy init

- src/cinder/gl/Context.cpp
In rare cases the target vector can exist but it will be empty.
> gl::context: check for empty vector before accessing .back()

- src/cinder/Log.cpp
Per #1109, we needed unique, non-zero EventIDs for windows logging in conjunction with a manifest file.  I believe this is what is holding up our WinRT logging.
My understanding based on some research, and [this](http://stackoverflow.com/questions/1755615/what-event-id-to-use-for-my-custom-event-log-entries) post, is that EventID values are application specific, so the use of 100, 101, etc, should't pose an issue in windows.  I just need to explicitly document this in the windows section of the logging guide.
> Supplying valid EventID values for windows logging

- samples/Earthquake/xcode/Info.plist
- samples/FlickrTestMultithreaded/src/FlickrTestMultithreadedApp.cpp
- samples/FlickrTestMultithreaded/xcode/Info.plist
- samples/Kaleidoscope/xcode/Info.plist
- samples/QuickTimeAdvanced/xcode/Info.plist
- samples/flickrTest/src/flickrTest.cpp
- samples/flickrTest/xcode/Info.plist
Introduced in OS X 10.11 and iOS 9, [App Transport Security](https://developer.apple.com/library/prerelease/ios/technotes/App-Transport-Security-Technote/) requires a secure connection from app to a web service to prevent accidental disclosure and just generally be secure by default. A few samples load content via web service and exceptions are required in some cases to be runnable on 10.11+ / iOS 9+. In each case, the most narrow exception only to the immediate web service domain.
Samples were found via:
```sh
$ grep -r -i --include \*.cpp '"http' samples | less
```
The API request is (now) made over HTTPS, but unfortunately it doesn't support [forward secrecy](https://en.wikipedia.org/wiki/Forward_secrecy) so an exception is still required. Apparently all is well with the server …
> Support for App Transport Security on OS X and iOS

- samples/Kaleidoscope/xcode_ios/Instascope-Info.plist
Bring over c56a404 from the OS X Kaleidoscope project for iOS - it appears as though Kaleidoscope is the only iOS sample that requests a URL. Tested with the Xcode 7.1 Beta 2 / iOS 9 simulator.
The Kaleidoscope project also needs to link to the Accelerate framework, but I ran into another issue building with Xcode 7.x and I'm thinking many of the iOS samples need updates.
The `cinder_iphone_sim` scheme of the Cinder project itself seems to have gone sideways and refuses to build with Xcode 7.x. To work around it to test this particular issue, I killed the `cinder_iphone_sim` scheme and simplified to have the `cinder_iphone` scheme support both the device and simulator, `lipo`'ed the `lib/ios/` and `lib/ios-sim` boost libs together, and then simplified the Kaleidoscope project settings to …
> Support App Transport Security on iOS

- include/cinder/gl/scoped.h
- include/cinder/gl/wrapper.h
- samples/Earthquake/src/Earth.cpp
- samples/Earthquake/src/EarthquakeApp.cpp
- samples/Picking3D/src/Picking3DApp.cpp
- samples/QuaternionAccum/src/QuaternionAccumApp.cpp
- src/cinder/gl/scoped.cpp
- src/cinder/gl/wrapper.cpp
See the cited issues for changes. The main breaking change here is that `gl::enableAlphaBlending(bool)`'s boolean parameter is now not governing premultiplication but enablement.
#792, #1094, #1084
> Updating GL names for depth, stencil and alpha, per #792, #1094, #1084

- include/cinder/Log.h
- samples/Logging/src/LoggingApp.cpp
- src/cinder/Log.cpp
- test/DebugTest/src/DebugTestApp.cpp
Related to #1107
* LogManager's enable/disable routines were removed
* LogManager's interface was standardized with addLogger and removeLogger, etc
* LoggerMulti was removed and replaced with an internal vector of Loggers
* DebugTest was rewritten to be an easier to use test case
* Logger example updated
* Restructured locking so that there is no risk of crash, and wrote test case to confirm this
The good news is we now prevent a crash when adding and removing loggers from threads.  I confirmed the crash exists in the main branch, and confirmed the crash is fixed in this PR.
The bad news is that, in order to stop this crash, we had to move the lock mutex to the lowest level write() routine.  This really starts to show when you are logging from multiple threads.  
_For tests below, each …
> Logging restructure

- docs/htmlsrc/guides/cinder-blocks/index.html
The page wasn't rendering properly due to couple of broken tags and I've also removed the `armv7s` reference and replaced it with `arm64` given [glNext: removing armv7s](https://forum.libcinder.org/topic/glnext-removing-armv7s).
> Fix broken CinderBlocks guide render

- docs/htmlsrc/guides/boost/index.html
- docs/htmlsrc/guides/index.html
- docs/htmlsrc/guides/mac-setup/index.html
- docs/htmlsrc/guides/movie-writer/index.html
- docs/htmlsrc/guides/windows-setup/index.html
- docs/htmlsrc/index.html
Apparently my previous regex attempt still missed a bunch of cases of GitHub, Xcode and I've also added QuickTime to the mix as well as using https github links where relevant.
> More name normalization GitHub, Xcode and QuickTime

- include/cinder/audio/Node.h
- include/cinder/audio/cocoa/CinderCoreAudio.h
- include/cinder/audio/cocoa/ContextAudioUnit.h
- include/cinder/audio/cocoa/FileCoreAudio.h
- src/cinder/audio/Node.cpp
- src/cinder/audio/cocoa/CinderCoreAudio.cpp
- src/cinder/audio/cocoa/ContextAudioUnit.cpp
- src/cinder/audio/cocoa/DeviceManagerCoreAudio.cpp
- test/_audio/DeviceTest/src/DeviceTestApp.cpp
Use an audio::dsp::Converter if the Device used by an InputDeviceNode can't support the OutputDeviceNode's, and thereby entire Context's, samplerate. This is expected, as explained by Apple's [Technical Note TN2091](https://developer.apple.com/library/mac/technotes/tn2091/_index.html).
Also fixed a subtle bug I encountered during testing with NodeAutoPullable, where changes in connections resulted in a Node being 'auto pulled' created an inconsistent state.
> Audio Mac: allow for input samplerate != output samplerate

- docs/htmlsrc/guides/docs/building_docs.html
- docs/htmlsrc/guides/mac-setup/index.html
- docs/htmlsrc/guides/tour/hello_cinder.html
- docs/htmlsrc/guides/windows-setup/index.html
- docs/htmlsrc/index.html
Fixes part of the issue @computersarecool reported in #1182.
Might be worth merging into release_v0.9.0 if that's what on the site now?
> Fix download links and migrate links to https

- include/cinder/params/Params.h
- src/cinder/params/Params.cpp
Also adds a getPosition, getSize and setSize function to the InterfaceGl class.
I've added these functions in preparation of an updated Geometry sample. Due to the sheer number of tweakable parameters, I wanted to have the option to show or hide parameters based on the currently selected primitive.
Probably the only change up for debate is the public method ```OptionsBase::setVisible```, as it is the only public setter on the class. In the revised sample, I store all the parameters in a ```vector<OptionsBase>```, so I need a method on this base class to show and hide individual parameters. Perhaps the other setters should become public as well. The only drawback I can think of is that they will show up in the auto-completion dialog, making it bit harder to create a parameter using the …
> Allows showing or hiding an existing parameter.

- include/cinder/gl/wrapper.h
- src/cinder/gl/wrapper.cpp
```gl::stencilMask``` took a GLbool instead of a GLuint.
> Fixed parameter type to glStencilMask.

- src/cinder/gl/Fbo.cpp
And also added an extra case in the checkStatus method to deal with incomplete layered fbo.
See discussion https://github.com/cinder/Cinder/issues/1191
> Updated Fbo::attachAttachments to modern opengl on desktop

- src/cinder/gl/ShaderPreprocessor.cpp
- test/_opengl/ShaderPreprocessorTest/assets/wrong_hash.glsl
- test/_opengl/ShaderPreprocessorTest/src/ShaderPreprocessorTestApp.cpp
- test/_opengl/ShaderPreprocessorTest/xcode/ShaderPreprocessorTest.xcodeproj/project.pbxproj
Replaces regex's we've been using for preprocessing `#version` and `#include` directives in GLSL with handwritten equivalents. The primary motivation is to remove our dependency on std::regex to simplify Linux + GCC ports. A secondary benefit is improved performance, on MSW in particular. These changes benchmark as 5.5x perf in Debug and 3.7x perf in Release for me.
> GLSL preprocessor regex replacement

- include/cinder/GeomIo.h
The constructor should just accept a float, but it was asking for a non-const float reference.
Now allows for the very reasonable usage:
```c++
auto thing = geom::Sphere() >> geom::Constant(geom::Attrib::CUSTOM_0, 1.0f);
```
Before, required the somewhat absurd:
```c++
auto one = 1.0f;
auto thing = geom::Sphere() >> geom::Constant(geom::Attrib::CUSTOM_0, one);
```
> Fix geom::Constant float constructor.

- android/CMakeLists.txt
This was addressed by [chaoticbob/Cinder/pull/77](https://github.com/chaoticbob/Cinder/pull/77) but was lost in the android_linux handover shuffle.
> Add Base64.cpp to the Android build

- src/cinder/gl/Fbo.cpp
***Really sorry about this!***
My last changes have broken our dear FboCubeMap class! I'm not sure how, but it seems like I missed this in the tests I've done for my last PR.
I'll start working on a better solution, but for now this fix the issue.
What was happening is that using ```glFrameBufferTexture``` with a cubemap texture (instead of ```glFrameBufferTexture2D```) makes the Framebuffer expect a depth attachement of the same target (and therefore a cubemap depth attachement / 6 faces depth attachement). Ideally this should be dealt with when creating the depth buffer, checking for the format there, but this involves other changes and it's probably better to make that happen with a few other changes that we recently discussed.
Sorry again!
> Fixed issue with FboCubeMap from previous PR

- include/cinder/Rect.h
- src/cinder/Rect.cpp
For parity with Area, which has the same methods.
> RectT::moveULTo(), getMoveULTo()

- include/cinder/app/TouchEvent.h
Using this in a multi-touch aware scene graph to know when a node handled some of a TouchEvent's touches, but not all, without the Node having to remove the Touch itself.
> Added TouchEvent::Touch::setHandled() / isHandled() flag.

- src/cinder/app/cocoa/PlatformCocoa.cpp
- test/DisplayTest/xcode/DisplayTest.xcodeproj/project.pbxproj
Unlikely to be a big deal, but the `NSScreen` instances were retained without a paired release - I think it was forgotten from ed74713b. Quickly verified via _test/DisplayTest_.
> Fix leaked NSScreen instances from app::PlatformCocoa::getDisplays()

- samples/_opengl/DeferredShadingAdvanced/assets/common/unpack.glsl
- samples/_opengl/DeferredShadingAdvanced/assets/deferred/gbuffer.frag
I was seeing an issue on certain hardware (Windows 10, Nvidia GTX 970) where z-aligned normals would have their signs flipped, causing faces to disappear. Looking at the existing normal packing method, it normalized a zero-vector which I believe could have implementation-specific behavior.
[Per](https://forum.libcinder.org/topic/deferred-shading-normal-packing) @paulhoux, referring to [this article](http://aras-p.info/texts/CompactNormalStorage.html) on normal packing, I implemented the Lambert Azimuthal Equal-Area projection approach to the Spheremap Transform method, which should be equivalent to the existing method but fixed the issue I was seeing. I've attached before and after screenshots from the DeferredShadingAdvanced sample that show pretty similar results with the two …
> Fix normal packing with z-aligned normals in DeferredShadingAdvanced

- include/cinder/Camera.h
- src/cinder/Camera.cpp
Lens shift was not taken into account. Also added 'override' keyword to virtual functions in derived classes. Use the CameraPersp sample if you want to check the implementation: the red line is the generated Ray, but it is not correct when lens shift is applied. This code will fix that. See also issue #1239 .
> Fix for CameraPersp::generateRay

- docs/htmlsrc/_templates/master-template.mustache
Fixes #1246.
http://www.w3.org/wiki/HTML/Elements/input/text has some documentation for the attribute.
> Disable search box's autocomplete

- include/cinder/app/AppBase.h
- include/cinder/app/Platform.h
These were already on `app::Platform` as abstract virtual methods, this just adds some inline methods for those in AppBase.h so they are easier to find.
> add back app::getResourcePath() / app::getResourceDirectory()

- docs/generateDocs.py
- docs/htmlsrc/_assets/css/style.css
- docs/htmlsrc/_assets/js/cinder.js
- docs/htmlsrc/_docs/log/Logger.html
- docs/htmlsrc/guides/audio/index.html
- docs/htmlsrc/guides/cinder-blocks/index.html
- docs/htmlsrc/guides/docs/building_docs.html
- docs/htmlsrc/guides/index.html
- docs/htmlsrc/guides/logging/index.html
- docs/htmlsrc/guides/mac-setup/index.html
- docs/htmlsrc/guides/tour/hello_cinder.html
- docs/htmlsrc/guides/windows-setup/index.html
- docs/htmlsrc/index.html
- docs/stylesrc/stylus/cinder_docs.styl
- include/cinder/audio/InputNode.h
Rebased the various docs commits mentioned in https://github.com/cinder/Cinder/issues/1213 onto the release_v0.9.0 branch so we can update the website. 
Fixes #1135 & #1245.
Here's the `git rebase -i origin/release_v0.9.0` commands I used:
* * *  
#1148 Updated git guide. Fixed outdated/broken links.
pick f0c04ba49cfbe91a224132e4af184ca4d552dab3 Updated index docs links
#pick f1b930f432582c01846651d379251ec3de15a8c6 Merge to resolve conflicts
#1149 Added logging guide
pick 6d1220fdb9e5281c174557a2d5469901900eccbf Added logging guide
pick 5c3eb4212a2b6147b06e52dd1a07e586cb504b6e Formatting updates based on feedback
#1150 Added supplementary html for LoggerFile and LoggerFileRotating 
pick 0bab421cbc4484dbcd9d8639a3a9380a2f507701 Added supplementary html for LoggerFile and …
> Backport docs changes to release_v0.9.0 branch

- include/cinder/CameraUi.h
- src/cinder/CameraUi.cpp
Fixing CameraUi not testing for enabled in signal handlers, and adding isConnected() method. Addressing #1283.
> CameraUi events

- .gitignore
They were showing up as untracked content whenever I ran a sample.
> ignore the .VC.opendb files created by VS 2015

- samples/_opengl/MotionBlurVelocityBuffer/src/MotionBlurVelocityBufferApp.cpp
Now-default alpha blending broke the velocity buffer rendering.
Simply disabled the alpha blending.
Closes #1055 (at least on OSX)
> Fix velocity buffer motion blur sample.

- include/cinder/Cinder.h
I'm using Paul's upcoming video stuff  in a project and I was able to just drop into into my project except for [this change](https://github.com/cinder/Cinder/compare/cinder:7182b3a...paulhoux:8392693#diff-d952cf3677246763cc7566adede21863). He's using the macros defined within that windows header throughout his code base to make sure MF isn't used before vista.
Also we're already including similar headers for Mac (TargetConditionals.h, AvailabilityMacros.h), and I do think it is nice to use the macro names like `#if( _WIN32_WINNT >= _WIN32_WINNT_VISTA )` rather than 0x600 or whatever. This header doesn't #include any other windows headers so it is pretty lightweight.
> include sdkddkver.h in Cinder.h

- src/cinder/ImageSourceFileWic.cpp
I ran into some client-provided jpeg's that were encoded in CMYK format, was getting the `ImageIoException` that explains its an 'unsupported format' but didn't know why at first. This'll make it clear that we don't support cmyk color model..
> detect CMYK files and throw more detailed exception.

- include/cinder/gl/Batch.h
- src/cinder/gl/Batch.cpp
Cleans up the VertBatch code and fixes the error on RPI2 mentioned [here](https://forum.libcinder.org/topic/params-won-t-compile-on-pi#23286000002630003)  by @chaoticbob 
Also fixes a problem where the Vao pointer is set to nullptr on clear when using default buffers.
This example fails on current master:
```c++
// setup
mBatch = gl::VertBatch::create( GL_POINTS, true );
// draw
mBatch->begin( GL_LINE_STRIP );
for( const vec2 &point : mPoints ) {
mBatch->vertex( vec4( point, 0, 1 ), Color( 1.0f, 0.5f, 0.25f ) );
}
mBatch->draw();
```
> VertBatch cleanup

- blocks/OSC/src/Osc.cpp
- blocks/OSC/src/Osc.h
- blocks/OSC/test/Test/src/TestApp.cpp
- blocks/TUIO/src/Tuio.cpp
- Fixed edge case in Tuio. In the spec, the source message is optional and in production this was breaking Tuio. Added an address to Osc Messages and use that address as a "source" in Tuio.
- Also implemented socket shutdown for Osc, which fixes a problem people were having with opening a socket soon after closing it. However, there are still edge cases, which can be seen [here](http://stackoverflow.com/questions/35365826/asio-address-already-in-use-on-bind-yet-i-can-still-connect/35394556#35394556).
> Osc and Tuio updates

- samples/FlickrTestMultithreaded/src/FlickrTestMultithreadedApp.cpp
Fixed a bug in the Flickr Multi-threaded sample. 
In its previous form, the fence ensured that only the gl commands sent _before_ texture::create() were completed. This can lead to incomplete textures after the fence, specifically with the following call to gl::texture::create().
Quick fix that pushes gl::Sync::create() and clientWaitSync next to each other. This will properly block until all work, including gl::texture::create(), is complete.
> Fixed gl::Sync Position in Flickr Multi-threaded Sample

- blocks/OSC/src/Osc.h
This fixes a problem with the way vc2013 handles atomic types. Solution found [here](http://stackoverflow.com/questions/15750917/initializing-stdatomic-bool). Fixes #1405
> Fixing vc2013 handling of std::atomic

- include/cinder/Rect.h
- src/cinder/Rect.cpp
Rectifies (har har) one case where the copying (past tense) methods don't match the in-place.
> Add vec2 overload of RectT::scaledCentered()

- src/cinder/gl/ShaderPreprocessor.cpp
- src/cinder/qtime/QuickTimeGlImplAvf.cpp
This caused build errors on case-sensitive filesystems.
> Build fix: Fixed file names in include

- include/cinder/audio/msw/FileMediaFoundation.h
- src/cinder/audio/Target.cpp
- src/cinder/audio/msw/FileMediaFoundation.cpp
The result should be an empty .wav file, but shouldn't crash (previously on Windows, an assertion was failing causing the program to abort).
> Handle writing zero frames to an audio::TargetFile

- src/cinder/audio/InputNode.cpp
- src/cinder/audio/OutputNode.cpp
- src/cinder/audio/msw/DeviceManagerWasapi.cpp
- test/_audio/DeviceTest/src/DeviceTestApp.cpp
Previously the MSW Media Foundation implementation would blow up on an assertion failure if you tried to make a default audio input or output device and there wasn't connected hardware for that. Now the solution is as follows:
* `Device::getDefault[Input|Output]()` will return nullptr (empty `DeviceRef`) if there is no input or output device.
* Calling `Context::create[Input|Output]DeviceNode()` will cause an exception to be thrown if there is no default input or output device. This can be avoided by first querying for the default input or output device node before doing any other audio graph configuration.
> Handle no available audio device in a recoverable manner.

- src/cinder/audio/SampleRecorderNode.cpp
Now mWritePos gets updated in process() through std::atomic::compare_exchange_strong().
The update only happens if mWritePos didn't change since the beginningof process().
If it did change, then it means mWritePos has been reset to 0 by anotherthread calling start() and
therefore it must not be updated ( by adding numWriteFrames to it ) or the new recording will start with an offset of numWriteFrames from the beginning of the buffer.
> Fixed write position bug in BufferRecorderNode::process()

- src/cinder/app/linux/AppImplLinuxGlfw.cpp
This fixes a crash on exit that happens currently when you quit the app through `ci::app::quit` . The reason is that currently `ci::app::quit` calls `::glfwTerminate` which invalidates and destroys all windows immediately but since this can happen from callbacks there is no guaranty that [`::glfwPollEvents`](https://github.com/PetrosKataras/Cinder/blob/6ddaa339551b32ee2638f0ca42a9019453a1a2e7/src/cinder/app/linux/AppImplLinuxGlfw.cpp#L310) will not be called from the run loop after all windows are destroyed which leads to a crash internally on X.
With this PR windows are flagged as ready to close inside `ci::app::quit` and are actually closed inside the run loop after `::glfwPollEvents` has finished, keeping the exit order sane.
> Use glfwSetWindowShouldClose for signalling quit. Fixes exit crash.

- src/cinder/app/linux/PlatformLinux.cpp
It seems that paths coming from Zenity contain a newline character at the end. This messes up filenames that then appear with this character ending. Use the ObjLoader sample as a test case to reproduce. The fix should not affect other DialogHelpers.
> Linux fix DialogHelper(Zenity) newline ending.

- src/cinder/app/linux/PlatformLinux.cpp
As is [currently](https://github.com/cinder/Cinder/blob/android_linux/src/cinder/app/linux/PlatformLinux.cpp#L409) `getDefaultExecutablePath` will return the full symlink path to the exe including the exe itself. This fixes it by returning the parent dir of the exe as it happens on the other platforms too.
> Fix Linux version of getDefaultExecutablePath to return parent dir path of the exe.

- proj/cmake/libcinder_configure_build.cmake
- proj/cmake/libcinder_source_files.cmake
- proj/cmake/libcinder_target.cmake
- proj/cmake/platform_msw.cmake
This gets things closer to building on windows, at least when generating a Visual Studio project (which isn't very useful in our case). When trying to build from the command line, not only is it incredibly involved to set up the build system, it doesn't look like gcc / libstdc++ support some of the things we'd need to build libcinder, such as `std::mutex`, so I stopped there.
I only added changes here that won't have an effect on other platforms, as part of due diligence towards #1301.
> WIP building with cmake on Windows

- include/cinder/app/AppBase.h
- src/cinder/app/AppBase.cpp
- src/cinder/app/cocoa/AppCocoaTouch.cpp
- src/cinder/app/cocoa/AppImplMac.mm
- src/cinder/app/cocoa/AppMac.cpp
- src/cinder/app/linux/AppImplLinuxGlfw.cpp
- src/cinder/app/linux/AppLinux.cpp
- src/cinder/app/msw/AppImplMswBasic.cpp
- src/cinder/app/msw/AppMsw.cpp
This should address 3 issues related to `quit()`. 
* #1072 where `quit()` called from the app constructor had no effect
* `quit()` called from `update()` or `draw()` required an additional event (like a mouse move) for it to take effect on OS X
* `draw()` could be called even though `quit()` was called from `update()`
These should all be fixed and tested on OS X, Linux, and MSW, using the code below:
```
#include "cinder/app/App.h"
#include "cinder/app/RendererGl.h"
#include "cinder/gl/gl.h"
#define TEST_QUIT_IN_CONSTRUCTOR
//#define TEST_QUIT_AT_SETUP
//#define TEST_QUIT_IN_UPDATE
class QuitTestApp : public ci::app::App {
public:
QuitTestApp();
void setup() override;
void update() override;
void draw() override;
bool    mQuitCalledFromUpdate, mQuitCalledFromConstructor, …
```
> quit()-centric app fixes

- src/cinder/app/cocoa/RendererImpl2dMacQuartz.mm
- src/cinder/cocoa/CinderCocoa.mm
Possible fix for issue #1454. 
In the Wisteria example, copyWindowSurface() is called from a key event, which means the CGContextRef currentRef has been released already by the finishDraw method in RendererImpl2dMacQuartz.mm.
This PR adds a check for the currentRef, and will create a temporary reference if needed.
I think the NSBitmapImageRep was also being released twice, since it's called by convertNsBitmapDataRep with "assumeOwnership" set to true, which should take care of clean-up.
Finally, I noticed that the channel order coming from initWithFocusedViewRect was ARGB instead of RGBA. Updated convertNsBitmapDataRep accordingly. (But not sure if this will break something elsewhere?)
Open to any feedback / revisions / insights. Thank you.
> Make sure CGContext exists before attempting to get window contents.

- include/cinder/app/AppBase.h
- include/cinder/app/cocoa/AppMac.h
- src/cinder/app/cocoa/AppMac.cpp
By default Xcode has this option enabled, which introduces 2 additional command line arguments, `NSDocumentRevisionsDebugMode YES`
For cases requiring cross-platform argument parsing, this is obviously frustrating, especially since this is adjusted through the Xcode scheme rather than project settings. This PR takes the same approach that [wxWidgets takes](https://groups.google.com/forum/#!msg/wx-dev/FW6yHFFLA6Y/RLIaNADxkFIJ). Here's some [relevant discussion](https://bugs.chromium.org/p/skia/issues/detail?id=2976) on the Skia list as well.
> Fixing Xcode-induced annoyance -NSDocumentRevisionsDebugMode

- blocks/Cairo/include/cinder/cairo/Cairo.h
- blocks/Cairo/src/Cairo.cpp
- include/cinder/Channel.h
- include/cinder/Surface.h
- include/cinder/cocoa/CinderCocoa.h
- include/cinder/gl/Texture.h
- include/cinder/ip/Threshold.h
- include/cinder/msw/CinderMswGdiPlus.h
- src/cinder/Channel.cpp
- src/cinder/Surface.cpp
- src/cinder/cocoa/CinderCocoa.mm
- src/cinder/gl/Texture.cpp
- src/cinder/ip/Blend.cpp
- src/cinder/ip/Blur.cpp
- src/cinder/ip/Checkerboard.cpp
- src/cinder/ip/EdgeDetect.cpp
- src/cinder/ip/Fill.cpp
- src/cinder/ip/Flip.cpp
- src/cinder/ip/Premultiply.cpp
- src/cinder/ip/Threshold.cpp
- src/cinder/ip/Trim.cpp
Allow Surfaces larger than 2GiB
Previously creating surfaces larger than 2^31 bytes would cause an int32_t overflow on data size calculation, throwing a bad_alloc exception.
This commit converts mRowBytes, mInc and mRowInc to size_t, which causes size calculations to be performed in size_t before the result is used for array allocation and pointer arithmetic. Also, sites where these variables are used have been converted to avoid loss of precision.
> Allow Surfaces larger than 2GiB

- src/cinder/gl/TextureFormatParsers.cpp
it should respect the DDPF_FOURCC bit in the pixel format flags (often
absent in uncompressed dds files) and handle the case when fourcc is not
used.
> Fixed an issue with uncompressed dds texture

- docs/generateDocs.py
Crashing is avoided if group definition is undefined.
> Added check for glm group parsing

- proj/cmake/platform_linux.cmake
_same as #1493 but moved to an extra branch so the PR is not created from the android_linux branch._ 
This solves issues of linking the QuickTimeBasic example. 
On Linux the source files for the Movieplayer were never added to the cinder lib. 
As well as the glib library flag for the targets was missing.
> add missing files and libs to cmake for gstreamer

- proj/cmake/modules/cinderMakeApp.cmake
e.g. PCL (PointCloudLibrary) needs to call `target_link_libraries`
http://www.pointclouds.org/documentation/tutorials/using_pcl_pcl_config.php
```cmake
ci_make_app(
SOURCES           ${PROJECT_SOURCES}
INCLUDES          ${PCL_INCLUDE_DIRS}
CINDER_PATH       ${CINDER_PATH}
TARGET_LIBRARIES  ${Boost_LIBRARIES} ${PCL_LIBRARIES}
)
```
> Add TARGET_LIBRARIES param to ci_make_app

- src/cinder/gl/draw.cpp
Fixes #1279 
Thought I'd grab an easy one to cross off the list. I'm not sure if having only scoped texture bind is appropriate here, or if the function needs to save the existing context state first, and then restore it after drawing.
> Adds scoped texture binding to gl::drawEquirectangular

- blocks/OSC/samples/SimpleMultiThreadedReceiver/src/SimpleMultiThreadedReceiverApp.cpp
- blocks/OSC/samples/SimpleMultiThreadedSender/src/SimpleMultiThreadedSenderApp.cpp
Previously, a separate `io_service` was running, but the OSC objects were still using the application's primary `io_service`, which is processed on the main thread.
> Run OSC on separate thread in multithreaded samples.

- proj/cmake/platform_macosx.cmake
The qtime files are missing from the CMake build. Without this the QuickTimeBasic sample fails to link on OSX with CMake:
```
[100%] Linking CXX executable Debug/QuickTimeBasic.app/Contents/MacOS/QuickTimeBasic
Undefined symbols for architecture x86_64:
"cinder::qtime::MovieGl::getTexture()", referenced from:
QuickTimeSampleApp::update() in QuickTimeBasicApp.cpp.o
"cinder::qtime::MovieGl::MovieGl(boost::filesystem::path const&)", referenced from:
cinder::qtime::MovieGl::create(boost::filesystem::path const&) in QuickTimeBasicApp.cpp.o
"cinder::qtime::MovieBase::play(bool)", referenced from:
QuickTimeSampleApp::loadMovieFile(boost::filesystem::path const&) in QuickTimeBasicApp.cpp.o
"cinder::qtime::MovieBase::isDone() const", referenced from:
QuickTimeSampleApp::update() in …
```
> Added qtime files for CMake in OSX

- src/cinder/Serial.cpp
Previously, Cinder erroneously threw a Read error on failure to write.
> Throw SerialExcWriteFailure on failure to write.

- blocks/OSC/proj/cmake/OSCConfig.cmake
- blocks/TUIO/proj/cmake/TUIOConfig.cmake
These ones got missed with the recent changes.
> Fix source path for OSC and TUIO blocks.

- proj/cmake/libcinder_target.cmake
This change uses [cmake generator expressions](https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html) so that we can set the `-std=C++11/14` flag as PUBLIC on cinder target, without adversely affecting non-cpp files that get linked in.
This way anything that depends on cinder will automatically be compiled with the same cpp langage.
> Add CXX_FLAGS using target_compile_options(), only to cpp sources

- include/cinder/audio/dsp/RingBuffer.h
One of the issues in ##1551
cstring is needed to expose std::memcpy in RingBuffer.  OS X and Window must automatically include `<cstring>` in their build process.
> adding cstring to RingBuffer.h for std::memcpy

- CMakeLists.txt
- test/unit/proj/cmake/CMakeLists.txt
- test/unit/src/JsonTest.cpp
- test/unit/src/UnicodeTest.cpp
After doing 'make', to run the tests, do 'make test' (shows little output) or 'ctest -v' (shows more output) or
Debug/TestMain (bare metal, lets you use catch.hpp options).
> cmake: enable building and running catch-style unit test suite. 

- CMakeLists.txt
- test/unit/proj/cmake/CMakeLists.txt
- test/unit/src/JsonTest.cpp
- test/unit/src/UnicodeTest.cpp
Pretty minor, updates the recent additions from #1550 to match existing cmake code and in general the [style guide](https://github.com/cinder/Cinder/blob/master/CONTRIBUTING.md#style-guide).
Also updated the unit test cmake project name to match Xcode and Visual Studio.
> Unit test cmake whitespace

- test/unit/proj/cmake/CMakeLists.txt
Without this, 'make check' cannot find executable.
> Finish unit test exe rename from 82649fe75 

- include/cinder/audio/MonitorNode.h
- src/cinder/audio/MonitorNode.cpp
Only the FFT size needs to be a power of 2.
> Removed power of 2 restriction on MonitorNode's window size

- include/cinder/Arcball.h
If you include `cinder/Arcball.h` first in your project it does not compile because `CameraPersp` and `WindowRef` are not defined, only forward declared. Tested with clang on OS X.
> Added Arcball missing includes

- include/cinder/audio/MonitorNode.h
- include/cinder/audio/dsp/Dsp.h
- samples/_audio/InputAnalyzer/src/InputAnalyzerApp.cpp
- src/cinder/audio/MonitorNode.cpp
- src/cinder/audio/dsp/Dsp.cpp
- test/_audio/SpectralTest/src/SpectralTestApp.cpp
See https://en.wikipedia.org/wiki/Spectral_centroid.  After volume / loudness, this is arguably the most useful audio feature for doing visualizations and is quite simple to compute, so here it is.
> Added audio::MonitorSpectralNode::getSpectralCentroid()

- include/cinder/audio/msw/FileMediaFoundation.h
- src/cinder/audio/msw/FileMediaFoundation.cpp
- test/_audio/SampleTest/src/SampleTestApp.cpp
Fixes a bug that was reported quite a while ago but I couldn't reproduce until now - seems that some mp3s on windows hit the EOF marker before the actual reported frames, which was triggering an assert. For now, I fill the extra frames with silence. The only other option would be to change the internal `mFileNumFrames` property (and associated `mNumFrames`, the amount after samplerate conversion), but this could lead to client problems if they've already done some sizing based on `SourceFile::getNumFrames()`.  This is a rare enough case (only heard of it twice in the last year) that I think filling with silent frames is a better solution.
Also fixed some SampleTest issues and other SourceFileMediaFoundation cleanup.
> audio - SourceFileMediaFoundation improvements

- src/freetype/base/ftobjs.c
- src/freetype/base/md5.c
- src/freetype/base/md5.h
- Function collisions defined in freetype inhibit linking against openssl.
- Functions renamed with FT_*, which is the fix upstream in Freetype.
> Updating freetype to allow for openssl use

- include/cinder/audio/Device.h
- include/cinder/audio/OutputNode.h
- include/cinder/audio/cocoa/CinderCoreAudio.h
- include/cinder/audio/cocoa/DeviceManagerAudioSession.h
- src/cinder/audio/OutputNode.cpp
- src/cinder/audio/cocoa/ContextAudioUnit.cpp
- src/cinder/audio/cocoa/DeviceManagerAudioSession.mm
This adds handling for iOS interruptions (phone call, alarm, etc) and adds a fix for #997, a bug that was causing audio to glitch and drop out when the device slept, or another application was opened while audio was playing. In my tests audio now fades out smoothly when the app is backgrounded. There is no fade-in, but this is something users can add on a per-app basis.
I should mention that the interruption handling uses the iOS >= 6.0 API, as I've been told that 6.0 is going to be the new baseline.
> [iOS] Nix audio glitches during sleep and interruptions

- src/cinder/CaptureImplDirectShow.cpp
The surface cache uses a custom deleter for the Surface shared_ptr objects, but that custom deleter doesn't free up the allocated Surface objects. This small change cleans that that memory leak.
> Fixing small memory leak in DirectShow capture implementation

- blocks/OSC/proj/cmake/OSCConfig.cmake
- blocks/TUIO/proj/cmake/TUIOConfig.cmake
- blocks/TUIO/samples/TuioListener/proj/cmake/CMakeLists.txt
This fixes _unresolved linker errors_ for OSC and TUIO examples. As well as a typo fix to build the TuioListener example.
> Cmake osc tuio build fix

- src/videoInput/videoInput.cpp
Fixes bug mentioned in #1599 and removes some unnecessary code in the sourrounding function. 
The actual fix is contained in the first commit (just replacing ` s`with `S`)
The second commit is removing an unnecessary temporary string buffer
> Fix format string for wide string buffer

- src/cinder/app/msw/AppImplMsw.cpp
On my machine (running Windows 10), when I have a bug in my app's ```setup()``` function, Windows creates a ```MessageBox``` to show the error. This generates a ```WM_PAINT``` event which in turn calls the app's ```draw()``` function. Uninitialized member variables might then throw a new error, crashing the application. This is rather confusing. As a fix, I properly check if ```setup()``` has been called before calling ```draw()```. That way, the initial error message for which a ```MessageBox``` was created is shown, making debugging a lot easier.
> Fix for MSW MessageBox crash.

- include/cinder/gl/wrapper.h
- src/cinder/gl/wrapper.cpp
Adds cinder::gl::getVendorString() function which works similarly to cinder::gl::getVersionString() but for obtaining GL_VENDOR information.
> Added convenience gl::getVendorString().

- include/cinder/app/cocoa/AppImplMac.h
- src/cinder/app/cocoa/AppImplMac.mm
This is in addition to #1489 to fix the window position during the app's initial resize() call.
~~The position still seems to be off during `App::setup()`, I'm not sure yet if that can be fixed.~~ fixed with 1cbee56.
Test app code: http://pastebin.com/BReFbN2C
> (macosx) Fix window pos when on secondary display

- src/cinder/app/cocoa/AppImplMac.mm
In the current master, when the output window is not on the main screen, getWindowPosY() reports the incorrect Y position after moving the window once. This fixes that issue.
> fix (app impl mac): windowMovedNotification: use main screen as origin for coordinate space transformation

- include/cinder/Rand.h
- src/cinder/Rand.cpp
This PR simplifies the implementation of `ci::Rand` and the free functions in Rand.h. Mainly by
- Replacing the OS-specific seeding methods by std::random_device
- Replacing the hand-roled gaussian distribution reneration functions by `std::normal_distribution`.
I've run a few microbenchmarks to verify that this doesn't degrade the performance of the random number generation on my particular platform (VS2015 U3, Win10), but I can revert a particular change if someone knows for a fact that the stanard library facilities were not used for a particular reason.
> simplify rand

- include/cinder/PolyLine.h
This let's me simplify some code like:
```c++
ci::PolyLine2f BuildingPlan::triangle()
{
ci::PolyLine2f result( { ci::vec2(10, -10), ci::vec2(10, 10), ci::vec2(-10, 10), ci::vec2(10, -10)  } );
result.setClosed();
return result;
}
```
Down to a one liner.
```c++
ci::PolyLine2f BuildingPlan::triangle()
{
return ci::PolyLine2f( { ci::vec2(10, -10), ci::vec2(10, 10), ci::vec2(-10, 10), ci::vec2(10, -10)  }, true );
}
```
> PolyLine should accept closed at initialization

- include/cinder/PolyLine.h
- src/cinder/PolyLine.cpp
Following the pattern in RectT adding some methods to return copies rather than modifying in place.
> Add PolyLineT scaled() and offsetted().

- include/cinder/PolyLine.h
- src/cinder/PolyLine.cpp
- test/unit/src/PolyLineTest.cpp
- test/unit/xcode/UnitTests.xcodeproj/project.pbxproj
I'd been using [CGAL's Polygon_2](http://doc.cgal.org/latest/Polygon/classCGAL_1_1Polygon__2.html) to determine the orientation but realized the math isn't that complicated and would be a nice addition to the PolyLine class.
The algorithm is based of this answer the [FAQ for comp.graphics.algorithms](http://www.faqs.org/faqs/graphics/algorithms-faq/):
Subject 2.07: How do I find the orientation of a simple polygon?
Compute the signed area (Subject 2.01).  The orientation is 
counter-clockwise if this area is positive.  
A slightly faster method is based on the observation that it isn't
necessary to compute the area.  Find the lowest vertex (or, if 
there is more than one vertex with the same lowest coordinate, 
the rightmost of those vertices) and then take the cross product 
of the edges …
> Add methods to determine orientation of PolyLine

- include/cinder/audio/Exception.h
Now the error code of `AudioExc` is actually set and the unused `mDescription` member (which is already present in the base class) is removed.
> fix audio exception

- include/cinder/CameraUi.h
- src/cinder/CameraUi.cpp
Seemed cleanest to just centralize this in `disconnect()`. 
Fixes #1635 
Side note but what do people think about renaming `mMouseConnections` to just `mConnections`? I think the current name is a bit misleading since it has the window resize connection in there too.
> CameraUI should clear connections when changing window

- src/cinder/BSpline.cpp
- src/cinder/gl/Fbo.cpp
- src/cinder/gl/draw.cpp
More cases of parameters that are (probably) erroneously ignored
> fix ignored params 3

- src/cinder/app/msw/PlatformMsw.cpp
The MONITORINFOEX structure never got filled with data in this function.
Disclaimer:
This fix is based on immitating the neighboring function `getMonitorName()` and what I could put together from the MSDN documentation of the other involved functions - I've no actual experience with the windows API.
> Fix forgotton info querey in getMonitorBitsPerPixel()

- proj/cmake/modules/cinderMakeApp.cmake
Opening this for discussion. This is a solution for the problem mentioned in [this forum post](http://discourse.libcinder.org/t/rfc-cross-platform-cmake-support/102/25), where the assets fold can't be build when you build a cinder sample with something like:
```
cmake -DCINDER_BUILD_SAMPLE=Geometry ..
```
In order for this to work, the executable has to be placed in a subfolder, I used used the app name for this.
It looks for the assets folder in its common place by default (next to proj folder), but this can be overridden by passing in an argument for `ASSETS_PATH` to the `ci_make_app()` function. The symlink is currently always named `assets`.
Still to-do:
> symlink assets directory to be next to executable

- src/cinder/gl/ShaderPreprocessor.cpp
To my understanding, this is how the C preprocessor works as well when you include a `#pragma once` statement.
> Don't throw exception on circular include, return empty string instead

- src/cinder/app/linux/AppImplLinuxGlfw.cpp
This fixes cases where calls to glfw where issued after the library had been terminated ( test with the FlickrTestMultiThreaded sample ) and also adds the missing `cleanup()` signal before app termination.
> Fix early termination of glfw and add cleanup signal.

- src/cinder/gl/GlslProg.cpp
Updated findUniform( const std::string &name, int *resultLocation ) to have the same behavior as const findUniform( int location, int *resultLocation ) const. Currently one of the two methods breaks when trying to pass nullptr, while the other just skip it. This PR addresses this issue.
If I understand [the method's comment](https://github.com/cinder/Cinder/blob/master/include/cinder/gl/GlslProg.h#L441) correctly, it sounds like this should be the intended/expected behavior.:
```c++
//! Returns a const pointer to the Uniform that matches \a name. Returns nullptr if the uniform doesn't exist. The uniform location (accounting for indices, like "example[2]") is stored in \a resultLocation if it's non-null.
const Uniform* findUniform( const std::string &name, int *resultLocation ) const;
```
> Made GlslProg::findUniform( const std::string&, int* ) behavior closer to GlslProg::findUniform( int, int* )

- test/unit/proj/cmake/CMakeLists.txt
This should resolve #1672
Let me know if this is the proper way or if I should be pulling `UnitTests` out of the CMAKE project name, etc.
> Correcting path that unit tests run out of.  #1672

- include/cinder/gl/gl.h
- include/cinder/gl/wrapper.h
I added the defaults for `dispatchCompute()`'s numGroupsY and numGroupsX as it is the same as what happens in the compute shader's `layout( local_size_x = X​, ... )`, according to [this doc](https://www.opengl.org/wiki/Compute_Shader#Local_size).
> A couple minor compute shader additions

- src/cinder/app/cocoa/AppImplCocoaTouch.mm
Both `applicationDidEnterBackground` and `applicationWillEnterForeground` are called when the app is not in an active state. This change limits start/stopAnimation to being called when the app is visible to the user. This eliminates some glitches that occur when resuming a background app, which were due to the update/draw methods being called when the app was not visible.
> Start and stop animation only when the app active state changes

- .travis.yml
- proj/xcode/iosbuild-xcpretty.sh
- test/unit/src/JsonTest.cpp
- test/unit/src/SystemTest.cpp
- test/unit/src/audio/FftUnit.cpp
- tools/ci/cmake_test.sh
- tools/linux/scripts/trusty-install-deps.sh
- tools/osx/scripts/cmake-brew-install.sh
Addresses part of #1611, bandaid fixes #1263 
Adds Travis CI support for OS X (various xcode versions) and Ubuntu Trusty (14)
Specific changes
- Added an ios specific build script to proj/xcode.
- Wrapped this build in xcpretty since the verbosity of ios build breaks Travis (logs > 4MB)
- Modified the JsonTest to use the /tmp directory rather than the documents dir.  In a Travis env there is no documents dir.
- Disabled unimplemented system tests in SystemTest for linux
- Disabled FFT tests for non CINDER_MAC platforms
- Added scripts to tools/ for the following
- tools/ci/cmake_test.sh - walks through building debug and release versions of cinder via cmake
- linux/scripts/trusty-install-deps.sh - installs Trusty specific dependencies
- tools/osx/scripts/cmake-brew-install.sh - installs …
> Adds Travis CI support for OS X (various xcode versions) and Ubuntu Trusty

- include/cinder/Utilities.h
- src/cinder/Utilities.cpp
- src/cinder/gl/GlslProg.cpp
- test/unit/assets/test_load_write_string.txt
- test/unit/src/Utilities.cpp
- test/unit/vc2013/unit.vcxproj
- test/unit/vc2013/unit.vcxproj.filters
- Added writeString() to Utilities.h (only works with file targets for now)
- loadString() uses one less malloc / copy
- fixed a stray NUL that was getting written to shader sources in GlslProg::Format::setShaderSource()
- added unit test for round trip `loadString()` / `writeString()`.
Todo:
> String i/o improvements

- src/cinder/Utilities.cpp
cinder/utilities.cpp should include the `fstream` header (leads to compilation eror on VS2015 U3)
This pr also makes a few small formatting changes:
- delete some trailing whitespaces
- the opening `{` of a function is always on a new line
> fix include utilities

- include/cinder/Signals.h
- src/cinder/Signals.cpp
- test/unit/src/signals/SignalsTest.cpp
Utility to easily maintain a bunch of connections, disconnecting them when container is destroyed. Tying connections to an object's scope is vital in making sure runtime reloads are safe, and this makes it much easier to do so as compared to keeping a bunch of `ScopedConnections` (the dreaded mConnTouchBegan, mConnTouchMove, mConnBlah... anti-pattern).
Convenient syntax looks like:
```cpp
ci::signals::ConnectionList mConnections;
...
mConnections += getSignalXXX().connect( [this] { ... }; );
mConnections += getSignalYYY().connect( [this] { ... }; );
```
Right now it only accepts an R-value reference to a `Connection`, I'm not sure if we need anything more than this.
> Added signals::ConnectionList

- src/cinder/PolyLine.cpp
- test/unit/src/PolyLineTest.cpp
I split some of the 2D fixes out of #1698 so they can go in while we discuss the 3D parts. I add some quick tests for the methods I was touching.
The tests has a bunch of space indenting that I cleaned up so probably easiest to see what's changing there by [ignoring whitespace](https://github.com/cinder/Cinder/pull/1706/files?w=1)
> PolyLine template cleanups

- include/cinder/CinderMath.h
- include/cinder/Path2d.h
- include/cinder/Shape2d.h
- src/cinder/CinderMath.cpp
- src/cinder/Path2d.cpp
- src/cinder/Shape2d.cpp
- test/ShapeTest/include/Resources.h
- test/ShapeTest/src/ShapeTestApp.cpp
- test/ShapeTest/vc2013/Resources.rc
- test/ShapeTest/vc2013/ShapeTest.sln
- test/ShapeTest/vc2013/ShapeTest.vcxproj
- test/ShapeTest/vc2013/ShapeTest.vcxproj.filters
- test/ShapeTest/xcode/Info.plist
- test/ShapeTest/xcode/ShapeTest.xcodeproj/project.pbxproj
- test/ShapeTest/xcode/ShapeTest_Prefix.pch
With the current attention to text rendering and signed distance fields, I thought it would be a good idea to have proper functions in Cinder that will help us calculate distances from points to lines, quadratic curves and cubic curves. There was no functionality in `Path2d` or `Shape2d` for that yet.
In this PR, I have added proper, high quality algorithms to `CinderMath.h`. The `getClosestPointCubic()` method is quite involved, but compared to the implementation in Chlumsky's MSDFGEN library it is _between three and five times_ faster and _much_ more accurate. This will allow us to create much higher quality signed distance fields, without the need for additional libraries.
New methods in `Path2d` and `Shape2d` allow easy calculation of (signed) distances and/or finding the closest …
> Distance to curve.

- src/cinder/app/RendererGl.cpp
The CINDER_COCOA_TOUCH section of RendererGl is not using mStartDrawFn or mFinishDrawFn.  I'm assuming that it should be.  The fix makes it identical to the CINDER_MAC section.
> Use mStartDrawFn and mFinishDrawFn for CINDER_COCOA_TOUCH.

- blocks/__AppTemplates/__Foundation/vc2013/foundation.vcxproj
- blocks/__AppTemplates/__Foundation/vc2013_winrt/foundation.vcxproj
- proj/vc2013/cinder.vcxproj
- proj/vc2015_winrt/cinder.vcxproj
- proj/vc2015_winrt/cinder.vcxproj.filters
These are a bunch of small improvements to both `cinder.vcxproj` files and VS tinderbox templates, for both desktop and UWP.  The primary thing I addressed, as proposed in the #1429 comments, was that all build outputs for all configurations and platforms end up in the following folders:
Output Directory: $(ProjectDir)build\$(Platform)\$(Configuration)\
Intermediate Directory: $(ProjectDir)build\$(Platform)\$(Configuration)\intermediate\
This way, all of your build files can be easily blown away by deleting the folder called `build`, which is in line with how things usually happen on OS X and with CMake.
The next was to make the optimization settings a bit more consistent, as it was proposed in #1158 to always use `/MP` and disable `/Gm` flags. This was already happening, although in some …
> Visual Studio project file improvements

- include/cinder/app/TouchEvent.h
- src/cinder/app/cocoa/CinderViewCocoaTouch.mm
- src/cinder/app/cocoa/CinderViewMac.mm
Access is already exposed to the native touch (UITouch*) on iOS through TouchEvent::Touch::getNative().  This is useful for getting the force/pressure data for the apple pencil and other data.  In addition, I'd like to be able to get the UIEvent as well in order to be able to call predictedTouchesForTouch and coalescedTouchesForTouch at the application level.  Multi-touch is very laggy on iOS, which breaks the illusion of direct manipulation.  The predictive touches help out a lot.
> Expose native touch event

- samples/Extrude/xcode/Extrude.xcodeproj/project.pbxproj
It was complaining about a missing assets directory:
```
CpResource /Users/andrew/projects/Cinder/samples/Extrude/assets build/Debug/Extrude.app/Contents/Resources/assets
cd /Users/andrew/projects/Cinder/samples/Extrude/xcode
builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/andrew/projects/Cinder/samples/Extrude/assets /Users/andrew/projects/Cinder/samples/Extrude/xcode/build/Debug/Extrude.app/Contents/Resources
error: /Users/andrew/projects/Cinder/samples/Extrude/assets: No such file or directory
```
I opted to remove the reference it wasn't using any asset files.
> Fix Extrude sample

- include/cinder/PolyLine.h
- include/cinder/gl/draw.h
- src/cinder/gl/draw.cpp
- test/unit/src/PolyLineTest.cpp
Demonstrates a linking bug I've encountered:
```
Undefined symbols for architecture x86_64:
"cinder::PolyLineT<glm::tvec3<float, (glm::precision)0> >::reverse()", referenced from:
____C_A_T_C_H____T_E_S_T____11() in PolyLineTest.o
"cinder::PolyLineT<glm::tvec3<float, (glm::precision)0> >::reversed() const", referenced from:
____C_A_T_C_H____T_E_S_T____11() in PolyLineTest.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
[According to Travis](https://travis-ci.org/cinder/Cinder/builds/187942442) this only affects the Xcode builds.
If anyone know why that's happening I'd be happy to add the fix to this PR.
> PolyLine3d doesn't really work

- proj/cmake/modules/cinderMakeApp.cmake
Without this there is a mismatch between build type configuration and actual linking after a second configuration run.
i.e
During configuration and a call to `find_package`, if the package is found CMake, will create a cached variable `packagename_DIR` to hold the directory for finding the config file for the specific package. This means that if you then switch build type from debug to release, since this path is cached, CMake will still link with the debug version of Cinder and not the release one.
This PR unsets this var if previously set to ensure appropriate linking according to the build type.
You can check what is currently happening by building both Release and Debug versions of Cinder and then building a sample with :
`cmake .. && make VERBOSE=1`
and then
`cmake .. …
> Unset cached cinder config path if previously set.

- proj/cmake/libcinder_source_files.cmake
- proj/cmake/platform_linux.cmake
- proj/cmake/platform_macosx.cmake
This allows Cinder to build as a dynamic library on OS X using CMake. Tested with BasicApp and DeferredShadingAdvanced.
To test configure with `cmake .. -DBUILD_SHARED_LIBS=1` when building Cinder and from then on continue as usual.
> CMake: Fix Cinder dynamic lib target on OS X.

- include/cinder/audio/Buffer.h
- include/cinder/audio/Context.h
- include/cinder/audio/Node.h
- src/cinder/audio/ChannelRouterNode.cpp
- src/cinder/audio/Context.cpp
- src/cinder/audio/FileOggVorbis.cpp
- src/cinder/audio/InputNode.cpp
- src/cinder/audio/Node.cpp
- src/cinder/audio/OutputNode.cpp
This is #1670, conflicts resolved and a couple minor tweaks to how unused args are handled in ci::audio headers.
Related discussion in #1629.
> [warnings] Comment unused parameters in cinder/audio v2

- CMakeLists.txt
- proj/cmake/platform_macosx.cmake
- tools/ci/cmake_test.sh
This makes it easier to distinguish the variable as different to `CINDER_BUILD_SAMPLES=${name}`.
Also disabled building all samples (for now) in the CI script, since they don't all build yet.
> cmake: rename CINDER_BUILD_SAMPLES -> CINDER_BUILD_ALL_SAMPLES

- samples/CaptureCube/vc2013/CaptureCube.vcxproj
- samples/CaptureCube/vc2013/CaptureCube.vcxproj.filters
The project file for visual studio had the wrong name for the source file.
> fix capture cube vs2013 project file

- include/cinder/gl/GlslProg.h
- src/cinder/gl/GlslProg.cpp
Calling `glDeleteShader` on a shader after it is attached to a program flags it for deletion once it is no longer attached (e.g. When the program is deleted).
> Fix shader memory leak in GlslProg

- include/cinder/gl/Fbo.h
This was just throwing a linking error when used in an App.
> add missing Fbo::Format::setLabel implementation

- include/cinder/gl/Ssbo.h
Preprocessor definition to prevent Ssbo.h compilation on ES (specifically rpi2)
> Fixing compile error for Ssbo.h

- src/cinder/app/linux/PlatformLinux.cpp
- test/DisplayTest/src/DisplayTestApp.cpp
Stubbing out `PlatformLinux` display-related functions on EGL, where they are not supported.
> EGL display stub

- include/cinder/Stream.h
- include/cinder/UrlImplWinInet.h
- src/cinder/CinderMath.cpp
- src/cinder/UrlImplWinInet.cpp
- src/cinder/app/msw/AppImplMsw.cpp
- src/tinyexr/tinyexr.cc
- src/videoInput/videoInput.cpp
Again working on some warnings that VS puts out under W4
- Some unused local variables
- Calling the constructor of a virtual base class from a abstract class doesn't have any effect
- use `std::vector` to implement internal buffer of IStreamUrlImplWinInet (makes functions exception safe)
- Fix a bug in `getClosestPointQuadratic`, where number of solutions wasn't considered.
> Fix some warnings

- src/cinder/GeomIo.cpp
This addresses a bug found by @MikeGitb in #1764 in `Target::copyIndexDataForceTriangles()` which would manifest when using GL_TRIANGLES primitive with 16-bit indices. Additionally, this PR asserts that indices are within range in the 16-bit index case. Unfortunately I don't see an easy way to unit test that this assert fires using Catch. The code I used to exercise it is below.
```
vector<uint16_t> idx16( 10 );
vector<uint32_t> idx32;
for( size_t i = 0; i < idx16.size() - 1; ++i )
idx32.push_back( (uint32_t)i );
idx32.push_back( 65536 ); // failure case
geom::Target::copyIndexDataForceTriangles( geom::Primitive::TRIANGLES, idx32.data(), idx32.size(), 0, idx16.data() );
```
> copyIndexDataForceTriangles bugs

- src/cinder/ImageSourceFileRadiance.cpp
**TL;DR;** The fix is to check for EOF at the start of the line scanning method instead of the end so we don't skip the last line.
**Details:**
The core of the RADIANCE/HDR/RBGE file decoder does this:
```c++
for( int y = height - 1; y >= 0; y-- ) {
if( ! decrunchScanline( scanline.get(), width, stream.get() ) )
break;  /// <<< if we hit this, we miss a line!
workOnRgbeScanline( scanline.get(), width, cols );
cols += width * 3;
}
```
... where ```decrunchScanline(...)``` deals with unpacking the RLE bytes that are compressed into a non-compressed format that ```workOnRgbeScanline``` then converts into a 3-float value scanline.
```c++
bool decrunchScanline( RgbePixel *scanline, int len, IStreamCinder *stream )
{
...
// while we have bytes to read from the stream ...
while( ... ) {
...
// …
```
> Adding off-by-one fix for RADIANCE parser

- include/cinder/Signals.h
- src/cinder/Signals.cpp
- test/unit/src/signals/SignalsTest.cpp
Was no longer being generated on clang since the explicit && versions were added in #1676, causing some code to break (such as in https://github.com/simongeilfus/Cinder-ImGui/pull/31).
Added a simple unit test with this code that now passes.
> explicitly add signal::Connection copy constructor and assignment operator

- src/cinder/gl/Texture.cpp
Fixes #1763. Before this (since android_linux branch merge), loading custom mipmaps was broken.
>  setting mMaxMipmapLevel in Texture2d

- include/cinder/gl/ShaderPreprocessor.h
- src/cinder/gl/ShaderPreprocessor.cpp
- test/unit/src/ShaderPreprocessorTest.cpp
Solves the issue brought up in #1744, where the PostProcessingAA sample was issuing multiple `define()`s for the same macro, and due to `ShaderPreprocessor` being stored on the `GlslProg::Format` as a shared_ptr now, this resulted in duplicate defines. Solution we decided on was that additional `#define` directives will overwrite previous ones.
The directives are stored as a `<macro string, value string>` pair now, simplifies bookkeeping at basically no extra processing or memory cost.
> ShaderPreprocessor gracefully handles duplicate #defines, add way to remove #defines

- include/cinder/Path2d.h
- samples/BezierPath/src/BezierPathApp.cpp
- src/cinder/Path2d.cpp
- src/cinder/gl/draw.cpp
- test/unit/src/Path2dTest.cpp
Adds a new `Path2d::getSubPath()` method, which allows extracting a range of a Path2d, similar to trim curves in After Effects.
The image below shows a subPath extracted at (0,⅓), (⅓,⅔), and (⅔,1).
Note this PR also changes the `wrap` parameter's default value to `false` for `calcNormalizedTime()` and `calcTimeForDistance()`.
> Adds sub-path functionality to Path2d

- .appveyor.yml
- .appveyor_winrt.yml
For AppVeyor this will only checkout boost, not tinderbox, which will speed things up slightly.
Currently can not do this on TravisCI
> Only checkout boost submodule.

- include/cinder/Json.h
- include/cinder/Utilities.h
- include/cinder/Xml.h
- src/cinder/Json.cpp
- src/cinder/Log.cpp
- src/cinder/audio/Source.cpp
- test/unit/src/Utilities.cpp
Removing `boost::lexical_cast`, particularly in `toString()` and `fromString()`. Note that this may represent a performance regression in some instances, but `toString()` and `fromString()` are meant purely for convenience.
> Removing boost::lexical_cast

- docs/htmlsrc/guides/git/index.html
- Path in docs is currently cinder/xcode/fullbuild.sh, but
the script is actually at cinder/proj/xcode/fullbuild.sh
> Fix path for xcode/fullbuild.sh in docs

- include/cinder/CinderAssert.h
- src/cinder/CinderAssert.cpp
- test/DebugTest/src/DebugTestApp.cpp
- test/DebugTest/vc2015/DebugTest.vcxproj
Addresses issue brought up in #1804. This is important so that failed asserts show up in file logs.
Added a new handler for `CI_ASSERT()` so we can route it to `ci::log()` too, as before it was using the std version of `assert()`.
> assertion handlers use ci::log

- docs/htmlsrc/guides/linux-notes/rpi2.html
- docs/htmlsrc/guides/linux-notes/rpi3.html
- include/cinder/audio/linux/ContextPulseAudio.h
- include/cinder/gl/platform.h
- samples/_audio/InputAnalyzer/src/InputAnalyzerApp.cpp
- src/cinder/audio/linux/ContextPulseAudio.cpp
- src/cinder/audio/linux/DeviceManagerPulseAudio.cpp
- test/_audio/DeviceTest/proj/cmake/CMakeLists.txt
- test/_audio/common/AudioTestGui.h
New features:
- implemented `InputeDeviceNode` (microphone input)
- you can specify a hardware device with `Device::findDeviceByName()`
- latency improvements. Default is set to 512 frames per block, as is the default on other platforms. You can adjust that to be whatever size you want (rounded to a power of 2) with the usual `Device::updateFormat()` method.
I also added a bunch of error handling, in the way of exceptions or asserts. So if something was silently failing before, it might not be so silent anymore. :)
I think that the pulse stuff could use a refactor to use less private classes and be a little more direct, but I'm going to hold off on that for now as there will be a larger hardware versus offline audio pass at some point, and I'd rather wait for that to be in the works …
> linux Pulse Audio additions

- include/cinder/audio/dsp/Converter.h
Matches function documentation with the actual implementation: https://github.com/cinder/Cinder/blob/master/src/cinder/audio/cocoa/CinderCoreAudio.cpp#L92
> Fix documentation Converter::convert to match implementation

- proj/cmake/modules/cinderMakeApp.cmake
addresses #1776
To test this, generate a project with the cube sample before and after this addition.
```
$ mkdir build
$ cd build
$ $ cmake -DCINDER_BUILD_SAMPLE=_opengl/Cube -G"Visual Studio 14 2015 Win64" ..
```
> updated cmake to junction symlink in windows

- proj/cmake/configure.cmake
- proj/cmake/libcinder_source_files.cmake
- proj/cmake/modules/cinderMakeApp.cmake
- proj/cmake/platform_msw.cmake
- proj/cmake/utilities.cmake
A bunch of cmake stuff I've been meaning to take care of for a while:
- fixed logging utilities (`ci_log_v` and `ci_log_i`)
- added audio sources on Windows - successfully built and ran audio samples with a VS2015 generated project
- removed CLion workaround from before we were symlinking assets folders
- `CINDER_TARGET` gets populated in the CMakeCache.txt
> Misc CMake improvements

- src/cinder/Json.cpp
Proposed fix for #1863. jsoncpp appears to define `isDouble()` to be inclusive of integral types: https://github.com/cinder/Cinder/blob/master/src/jsoncpp/jsoncpp.cpp#L2706
I modified the `JsonTree::init()` method to consider doubles last so that integers are considered first. I believe this fixes the issue described.
> Addressing #1863, JSON misrepresenting integer value

- test/unit/src/JsonTest.cpp
Unit tests to confirm that JsonTree can make the serialization / deserialization round trip without incident.
These tests confirm issue #1863, and verify that pull request #1866 works.
Before #1866:
```
-------------------------------------------------------------------------------
Json
Cinder can accurately serialize and deserialize JSON values
-------------------------------------------------------------------------------
/Users/mika/Code/Cinder/test/unit/src/JsonTest.cpp:12
...............................................................................
/Users/mika/Code/Cinder/test/unit/src/JsonTest.cpp:176: FAILED:
CHECK( test32u.getValue() == JsonTree( test32u.serialize() )["uint32"].getValue() )
with expansion:
"4.29497e+09" == "4" …
```
> Added unit tests to check issue #1863 and pr #1866.

- src/cinder/audio/linux/FileAudioLoader.cpp
Fixes a bug where some .wav files were trying to be loaded with mpg123. I believe they were 32-bit floating point .wav files causing this issue.
> only consider file to be an mp3 if the extension is '.mp3'

- src/cinder/audio/linux/ContextPulseAudio.cpp
- src/cinder/linux/GstPlayer.cpp
Clang is unhappy using `libstdc++` in cpp14 (described [here](https://stackoverflow.com/questions/17775390/clang-3-3-in-c1y-mode-cannot-parse-cstdio-header)). These small tweaks allow Cinder to build with `-std=c++11`
> Clang builds with cpp11

- include/cinder/gl/Context.h
- src/cinder/gl/Environment.cpp
This is an imperfect solution to what appears to be a driver issue. When two threads call `wglMakeCurrent()` simultaneously, one can fail with either `ERROR_INVALID_HANDLE` or `ERROR_TRANSFORM_NOT_SUPPORTED`. Making the same call again succeeds. This PR attempts the same call a maximum of 10 times (with a millisecond of sleep in between) before throwing `gl::ExcContextMakeCurrent`. I've seen this behavior on both a GTX 970 and a GTX 780 under Windows 10, with a few different (recent) driver versions. I've created a stress-test app which (empirically) demonstrates this as a working fix. Not the most satisfying circumstances, but this was a really brutal failure to track down, and anecdotal Internet evidence points to others having similar issues and this approach fixing them.
> Retry on wglMakeCurrent() failure

- src/cinder/app/cocoa/AppImplCocoaTouch.mm
I've been experiencing an issue on iOS 11 where `screenDidDisconnect` can be called for a `UIScreen` that was not previously connected. This PR checks adds checks so that displays are only added once, and only removed if they exist.
> Prevent adding multiple of the same display and removing unconnected displays

- include/cinder/Utilities.h
- src/cinder/Stream.cpp
- src/cinder/Utilities.cpp
- test/unit/src/Utilities.cpp
Adds `swapEndian()` variants for 64-bit, some rudimentary unit tests to match, and Stream read/write methods.
> 64-bit Stream and endian operations

- include/cinder/audio/FileOggVorbis.h
- src/cinder/audio/FileOggVorbis.cpp
- src/cinder/audio/Target.cpp
I've added the ability to write .ogg files from ``TargetFile``.
Some work could still be done to expose encoder settings (e.g. the currently hardcoded ``mVorbisBaseQuality``). For now I've simply copied defaults from the Ogg Vorbis examples.
Questions:
* what's the recommended method to generate a random integer within Cinder? I've used ``Rand::randomize()`` and ``randInt()`` now, but this has some side-effects.
Be aware that this PR is not compatible with #1869. To merge both PR's, the constructor should be updated and ``getSampleRate`` should be replaced by ``getSampleRateTarget``.
> Added implementation of TargetFileOggVorbis

- proj/cmake/modules/FindGStreamer.cmake
GStreamer_FIND_VERSION isn't defined anywhere for me, so I had to do this change to FindGStreamer.cmake otherwise the gstreamer-1.0 include path wouldn't be passed to the compiler and compilation would fail.
I'm running Fedora 26.
> Fix FindGStreamer for cases when GStreamer_FIND_VERSION is undefined

- docs/htmlsrc/guides/resources/index.html
This edit fixes an issue where a large chunk of the resources guide gets cut off when the guide is generated, as reported by @richardeakin .
> [docs] Fixed html markup error in the resources guide.

- include/cinder/gl/Fbo.h
- src/cinder/gl/Fbo.cpp
Same as `Fbo::readPixels8u` but variant for HDR (floating point) attachments. Among other things pretty handy for debugging shaders, since you can write any variable out to that buffer and view it on the cpu side.
> Added Fbo::readPixels32f()

- src/cinder/audio/Source.cpp
read pos was being rounded to zero. Use case was when the `audio::Context` samplerate was 48000, and file being read / seeked was 44100.
> fix seek with samplerate conversion

- docs/htmlsrc/guides/windows-setup/index.html
As noted here: http://discourse.libcinder.org/t/links-to-cinder-git-broken-in-windows-setup-page/869
> Fixed outdated link to git guide

- include/cinder/app/msw/AppMsw.h
- src/cinder/Font.cpp
- src/cinder/Ray.cpp
- Unused parameters in the CINDER_APP macro are causing unused parameter warnings on msvc on W4
- Local variable name EPSILON clashes with global `#define EPSILON EPSILON_VALUE`
> Fix warnings

- include/cinder/audio/Context.h
- include/cinder/audio/Node.h
- src/cinder/audio/Context.cpp
- src/cinder/audio/Node.cpp
- src/cinder/audio/SamplePlayerNode.cpp
This solves a problem I ran into where you could schedule an `audio::Node` to be `disable()`d in the future, then something else tries to immediately `enable()` it, only to directly afterwards be disabled by the already scheduled event.
For now, solving by only allowing one scheduled event per node. Scheduling a new one, or calling `Node::enable()` / `Node::disable()`, will cancel the previously scheduled event. Can think about a scheme in the future for allowing multiple events to be scheduled, which would require a more intricate system that what is currently in place.
Deprecated the old `Context::schedule()` method, as there is now a `scheduleEvent()` and `cancelEvent()` pair.
> audio: Improve handling of overlapping scheduled enable / disable events.

- include/cinder/audio/msw/ContextWasapi.h
- include/cinder/audio/msw/DeviceManagerWasapi.h
- src/cinder/audio/msw/ContextWasapi.cpp
- src/cinder/audio/msw/DeviceManagerWasapi.cpp
In current master branch, your app will crash if the audio device being used on windows gets unplugged or disabled (originally reported in https://github.com/cinder/Cinder/issues/784). These changes will avoid that crash, and log to the console that the device was invalidated, along with which devices are connected / disconnected.
In order to play audio again, you will have to manually re-initialize the `audio::Context`'s `OutputDeviceNode`.  You can do this simply with:
```
ci::audio::master()->setOutput( ctx->createOutputDeviceNode() );
```
This is a temporary fix. The way I'd like to ultimately handle this is more involved, and parallels the work I began on OS X for keeping in sync with the system's default device. I plan to revisit that shortly, with a unified approach for both mac …
> MSW audio: Gracefully handle unplugged device

- src/cinder/Stream.cpp
- src/cinder/ip/EdgeDetect.cpp
- src/cinder/ip/Fill.cpp
- src/cinder/ip/Flip.cpp
- src/cinder/ip/Grayscale.cpp
- src/cinder/ip/Resize.cpp
- src/cinder/ip/Threshold.cpp
- src/cinder/ip/Trim.cpp
Removed the dependency on `BOOST_PP_*`, but using @vinjn's advice to keep the original macros
> Unrolled dependency on boost.preprocess

- src/cinder/audio/SamplePlayerNode.cpp
This can happen when you're loading an `audio::SourceFile` async, or in my case, when the source file fails to load. Beforehand, the `initialize()` method would crash.
> fix FilePlayerNode::initialize() when there is no source yet

- src/cinder/vk/Device.cpp
Device creation code is enabling all available extensions, but some extensions are exclusive. E.g. VK_KHR_maintenance1 cannot be used at the same time as VK_AMD_negative_viewport_height.
**How to test:**
On recent AMD drivers that expose these two extensions any Cinder Vulkan app will crash upon restart with VK_ERROR_INITIALIZATION_FAILED from vkCreateDevice.
> [Vulkan] Resolve incompatible extensions

- include/cinder/Utilities.h
- include/cinder/app/Platform.h
- include/cinder/app/cocoa/PlatformCocoa.h
- include/cinder/app/linux/PlatformLinux.h
- include/cinder/app/msw/PlatformMsw.h
- include/cinder/app/winrt/PlatformWinRt.h
- src/cinder/Utilities.cpp
- src/cinder/app/cocoa/PlatformCocoa.cpp
- src/cinder/app/linux/PlatformLinux.cpp
- src/cinder/app/msw/PlatformMsw.cpp
- src/cinder/app/winrt/PlatformWinRt.cpp
This PR implements `setThreadName()` for MSW, UWP, iOS, macOS, and Linux.
The behavior of this method is environment-specific. For example, in Visual C++ the results are visible immediately. In Xcode, they are only visible if you attach to a running app, rather than launching from within the IDE. In Linux they can be seen by executing `info thread` from gdb.
> setThreadName()

- include/cinder/Utilities.h
- src/cinder/Color.cpp
- src/cinder/Json.cpp
- src/cinder/Utilities.cpp
- src/cinder/Xml.cpp
- src/cinder/svg/Svg.cpp
- test/unit/src/Utilities.cpp
This removes additional dependencies on Boost, particularly of the string variety. It adds a `trim()` and `asciiCaseEqual()` method to _Utilities.h_, and matching unit tests.
I did not make the equivalent modifications to `JsonTree` as we are likely to deprecate this class soon.
> Boost string removal

- src/cinder/linux/GstPlayer.cpp
This ensures that no dangling messages are posted while the pipeline is switching states. The problem manifests on streaming video sources and it might be a GStreamer bug but in any case flushing the bus before resetting the pipeline solves it and probably makes more sense logically also in terms of order of descruction.
> Flush GstBus on deconstruction.

- include/cinder/gl/draw.h
- src/cinder/gl/draw.cpp
`gl::drawSolidTriangle` vertex parameters are `vec2` and if you call it with `vec3`'s they can get converted silently cutting the z-coordinate displaying the triangle in 2d instead of 3d. This simple PR is a modification of the function for `vec3` vertices to address this.
> gl::drawSolidTriangle with vec3 vertices

- .travis.yml
This PR removes xcode 8.1 and 8.2 from the test matrix with the goal of reducing travis-CI runtime. 
The remaining xcode versions are 7.3, 8 and 8.3 which should still cover most interesting cases. 
Currently, Travis seems to have some trouble anyway. Regardless of this however, I don't think testing on every version of XCode adds much value (unless you had problems in the past with a specific verion), but as travis is notoriously short on MacOS resources, it can greatly increase the ci runtime duration.
(Btw. I think we talked about this before somewhere, but I can't find the issue at the moment)
> [CI] Reduce test matrix on travis for xcode

- include/cinder/ConcurrentCircularBuffer.h
- include/circular/circular.h
- test/unit/src/Utilities.cpp
Modifications to `ConcurrentCircularBuffer` to remove Boost dependency. This uses Pete Goodliffe's implementation instead, which is included under the MIT license with permission from its author.
> Boostless circular buffer

- include/cinder/gl/GlslProg.h
- src/cinder/gl/GlslProg.cpp
Previous declaration was unimplemented. Removed 'Directives' suffix from the previous (unimplemented) method for consistency.
> implement GlslProg::Format::getDefines()

- src/cinder/Stream.cpp
Noticed this was missing while (locally) updating the Cinder-SdfText block.
> Missing CI_API dll macro for stream templated functions.

- src/cinder/gl/Texture.cpp
Which prevents 1d and 3d textures to be immutable / to use any recent GL functions that require the use of texture storage.
As can be seen in [`TextureBase::initParams`](https://github.com/cinder/Cinder/blob/master/src/cinder/gl/Texture.cpp#L254-L266) the `format.mMaxMipmapLevel` never get updated when [reaching this line](https://github.com/cinder/Cinder/blob/master/src/cinder/gl/Texture.cpp#L1742) if mipmapping is disabled. This results in passing a max level of zero to [this call](https://github.com/cinder/Cinder/blob/master/src/cinder/gl/EnvironmentCore.cpp#L182) to `glTexStorage3d`, which is [illegal (`GL_INVALID_VALUE is generated if width, height, depth or levels are less than 1. `)](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glTexStorage3D.xhtml).
The [`Texture2d` …
> Fixed issue that prevents Texture1d/3d to use glTexStorage

- include/cinder/msw/OutputDebugStringStream.h
Previously we've assumed ASCII strings on the Windows console but Visual C++ console supports UTF-8.
> Addressing MSW console() assuming ASCII strings

- src/cinder/audio/DelayNode.cpp
was causing nans when not using the `audio::Param` for delay seconds.
> audio::DelayNode: fix buffer read out of bounds when not ramping

- proj/cmake/modules/cinderMakeApp.cmake
The current CMake configuration links applications based on the current `CMAKE_BUILD_TYPE` so that a Debug ( or Release ) build of the application will link with the Debug( or Release ) build of Cinder.
This can be a reasonable default but there should be an option for the user to override this behavior if desired. 
This PR leaves the default behavior unchanged but adds support for applications to explicitly request the Cinder build type they would like to link with. 
This can be achieved now by configuring the application with 
`cmake .. -DCINDER_APP_LINK_RELEASE=1` to link with the Release version of Cinder
or
`cmake .. -DCINDER_APP_LINK_DEBUG=1` to link with the Debug version of Cinder.
Note that this option is relevant only when configuring/building the application with the …
> Add CMake option for linking applications with a specific Cinder build type ( Debug, Release )

- include/cinder/gl/TextureFont.h
- src/cinder/gl/TextureFont.cpp
A while ago it looks like `gl::TextureFont::drawStringWrapped()` was implemented on non-Cocoa platforms via liblinebreak. This uses the same methods to implement `measureStringWrapped()`. Neither are perfect, but it allows api parity while we still figure out the next text api.
> implement gl::TextureFont::measureStringWrapped() on non-Cocoa platforms

- include/cinder/CinderAssert.h
This makes it possible to enable assertions in a release build, without modifying your cinder repo (using CinderMswUserDefines.h in Windows or cmake defines on other platforms).
> added CI_ENABLE_ASSERTS macro

- include/cinder/gl/GlslProg.h
- src/cinder/gl/GlslProg.cpp
Useful in live coding setups when a shader in the GlslProg fails to compile: query getShaderType() and select the appropriate fallback.
Shouldn't have side effects, 1 member and 1 getter added.
> Added shader type member to GlslProg compile exception

- include/cinder/gl/TextureFont.h
Minor change to make it easy to use `gl::TextureFont` for its font atlas functionalities instead of its `drawString` methods. Useful when drawing any custom texts or characters.
This also exposes `gl::TextureFont::GlyphInfo` which shouldn't be a problem.
> Added public gl::TextureFont::getGlyphMap and getTextures

- include/cinder/msw/CinderMswGdiPlus.h
As reported over on the [Cinder-Runtime repo](https://github.com/simongeilfus/Cinder-Runtime/issues/32) I've been trying to integrate _Runtime_ with some of Bluecadet's blocks, and the [text rendering makes use](https://github.com/bluecadet/Cinder-BluecadetText/blob/30574dcecf077f129651ca3054ab5f7eeebd6fe8/src/bluecadet/text/StyledTextLayout.cpp#L569) of `ci::msw::createGdiplusBitmap()` which was previously not exported into the resulting cinder DLL.
Only that one function was needed, but I added the macro to all the functions to be safe. Also I'm not sure if it should get added to the `SurfaceConstraintsGdiPlus` class as well?
> Add CI_API macro to msw gdiplus functions

- src/AntTweakBar/TwBar.cpp
The included version of AntTweakBar does not support copying and pasting on Mac. This PR modifies AntTweakBar using a patch from Alec Jacobson (http://www.alecjacobson.com/weblog/?p=2378) to include support for it by calling out to the OS binaries `pbcopy` and `pbpaste`.
NB the shortcut is still CTRL+C and CTRL+V instead of CMD+C/CMD+V.
> Add support for copy/paste to AntTweakBar on Mac

- include/cinder/audio/Target.h
- src/cinder/audio/Target.cpp
See https://github.com/cinder/Cinder/issues/1629
Note, this is an abi and potentially API breaking change, but as it doesn't serve any purpose and has a default value I doubt this will be a problem.
> Allow override of filename extension in audio::TargetFile::create

- tools/linux/scripts/trusty-install-deps.sh
As mentioned in https://github.com/cinder/Cinder/issues/1964, apt might not find all the packages on a fresh ubuntu image (as e.g. on CI machine)
> [Linux Dep Install] Update apt package lists on linux

- include/cinder/linux/GstPlayer.h
- src/cinder/linux/GstPlayer.cpp
This PR contains some critical fixes for the case of multiple gst-gl pipelines running in parallel. It should address issues like the one described in the following forum post https://discourse.libcinder.org/t/gstreamer-linux-issue/1312 and also some other memory issues that would manifest deep in the GStreamer pipeline.
A note that these changes render #1947 obsolete. I could open a new PR with an updated patch for Windows once this is merged and assuming there is interest.
> GstPlayer GL fixes.

- src/cinder/audio/Context.cpp
- src/cinder/audio/Node.cpp
Fixing a couple shutdown bugs I ran into while working on `audio::ContextPortAudio`, which is different because it is a non-default audio context.
> Audio shutdown fixes

- include/cinder/qtime/QuickTimeGl.h
- proj/cmake/platform_msw.cmake
- src/cinder/linux/GstPlayer.cpp
This PR supersedes #1947 and adds support on MSW for video playback with GStreamer on top of the latest GstPlayer fixes ( #2039 ).
> Optional GStreamer support on MSW.

- blocks/OSC/src/cinder/osc/Osc.cpp
- blocks/OSC/src/cinder/osc/Osc.h
- blocks/OSC/test/Test/src/TestApp.cpp
- add method osc::Message::getSenderPort(), which returns the port of
the remote sender; a companion method to getSenderIpAddress().
- resolves issue #2041.
> Add OSC Message support to access the sender's port

- samples/CameraPersp/proj/cmake/CMakeLists.txt
- samples/FrustumCulling/proj/cmake/CMakeLists.txt
- samples/Kaleidoscope/proj/cmake/CMakeLists.txt
- samples/MandelbrotGLSL/proj/cmake/CMakeLists.txt
- samples/QuaternionAccum/proj/cmake/CMakeLists.txt
- samples/RDiffusion/proj/cmake/CMakeLists.txt
- samples/StereoscopicRendering/proj/cmake/CMakeLists.txt
- samples/SurfaceBasic/proj/cmake/CMakeLists.txt
- samples/TextTest/proj/cmake/CMakeLists.txt
- samples/VoronoiGpu/proj/cmake/CMakeLists.txt
This PR should fix compilation, through CMake, for the following samples :  
- CameraPersp
- FrustumCulling
- Kaleidoscope
- MandelbrotGLSL
- QuaternionAccum
- RDiffusion
- StereoscopicRendering
- SurfaceBasic
- TextTest
- VoronoiGpu
Partially addresses #2052
> CMake samples fixes.

- proj/cmake/libcinder_source_files.cmake
- src/cinder/Serial.cpp
This comes cheap since it shares the same unix implementation as macOS. `SerialCommunication` sample builds and runs also on Linux now. Relevant #2052.
> Enable ci::Serial on Linux.

- proj/cmake/modules/cinderConfig.buildtree.cmake.in
Solves issues with paths containing whitespaces. 
Came across this when trying out Visual Studio 2017 `Open Folder` feature where the default CMake configuration is something like `Debug (default)` and this reflects on the exported path. 
Using double quotes enforces a textual representation of the path which guards against any whitespaces.
> [CMake] Use quotes for targets filepath.

- samples/_timeline/TextInputTween/src/TextInputTweenApp.cpp
The content was in the upper right hand corner on recent Mac builds so I updated this sample to handle high density screens
Added setHighDensityDisplayEnabled() and passed prepareSettings into CINDER_APP
> Fixed centering issue on Mac

- include/glload/_int_glx_type.h
- include/glload/_int_glx_type.hpp
As discussed in #2064, this add compatibility for `glload` with newer version of Mesa.
> fix compile for Mesa 18.2.6 on some Linux

- src/cinder/System.cpp
The same code works in macOS and Linux. Only the required header files were needed to make it work.
> Making getNetworkAdapters() work on Linux

- src/cinder/app/linux/WindowImplLinuxGlfw.cpp
Filling in `Window::close()` in Linux/GLFW.
> Glfw window close

- test/CameraLensShiftTest/src/CameraLensShiftTestApp.cpp
- test/LineBreakTest/include/Resources.h
- test/LineBreakTest/src/LineBreakTestApp.cpp
- test/ScreenSaverTest/src/ScreenSaverTestApp.cpp
- test/XMLTest/src/XMLTestApp.cpp
- test/_opengl/ConvenienceDrawingMethods/src/ConvenienceDrawingMethodsApp.cpp
- test/_opengl/CubeMapLayout/src/CubeMapLayoutApp.cpp
- test/_opengl/QueryTest/src/QueryTestApp.cpp
- test/assetTest/src/assetTestApp.cpp
- test/base64Test/src/base64TestApp.cpp
- test/cmdLineArgs/include/Resources.h
- test/cmdLineArgs/src/cmdLineArgsApp.cpp
- test/resizeTest/Resources.h
- test/resizeTest/resizeTest.cpp
- test/streamFileTest/src/streamFileTestApp.cpp
Some of the test programs built with vc 2015 were fixed as it was the old Cinder specification.
assetTest   base64Test   CameraLensShiftTest
cmdLineArgs   LineBreakTest   TestScreensaver
streamFileTest  XMLTest
_opengl/
ConvenienceDrawingMethods   CubeMapLayout   QueryTest
Things that were difficult to fix and gave up:
cairoTest   mathTest   SignalsTest
> Fix test programs

- include/cinder/Plane.h
Without this fix `operator<<` cannot access the variables to be printed.
```
cinder/include/cinder/Plane.h:78:23: error: ‘cinder::PlaneT<float>::Vec3T cinder::PlaneT<float>::mNormal’ is private within this context
return o << "(" << p.mNormal << ", " << p.mDistance << ")";
```
> Fixed Plane ostream <<

- src/cinder/gl/ConstantConversions.cpp
Added when `CINDER_GL_HAS_COMPUTE_SHADER` is defined. Squashes some error log messages when using things like `uniform image2D` in compute shaders.
> added GL_IMAGE_NDs to constant conversion routines

- src/cinder/audio/Param.cpp
- test/_audio/AudioTest.msw/AudioTest.sln
- test/_audio/NodeTest/vc2015/NodeTest.vcxproj
- test/_audio/ParamTest/vc2015/ParamTest.vcxproj
This addresses a bug where `audio::Param::EventRef`s would accumulate when the context is disabled. They'd be cleared once you re-enable the context, but if you were to leave the audio context disabled for a long period of time, then a huge std::list would build up and the performance would degrade.
> audio: fix Param applyRamp() perf issue when context is disabled

- samples/_timeline/TextInputTween/proj/cmake/CMakeLists.txt
> sample: fix cmake config for _timeline/InputTextTween

- include/circular/circular.h
Simple fix to be able to use `ConcurrentCircularBuffer`.
Otherwise I get the following errors in macOS 10.12.6 with clang 9.0
```
in file included from cinder/include/cinder/ConcurrentCircularBuffer.h:28:
cinder/include/circular/circular.h:490:41: error: no member named 'equal' in namespace 'std'
return a.size() == b.size() && std::equal(a.begin(), a.end(), b.begin());
~~~~~^
cinder/include/circular/circular.h:499:42: error: no member named 'equal' in namespace 'std'
return a.size() != b.size() || !std::equal(a.begin(), a.end(), b.begin());
~~~~~^
cinder/include/circular/circular.h:508:17: error: no member named 'lexicographical_compare' in namespace 'std'
return std::lexicographical_compare(a.begin(), a.end(), b.begin(), b.end());
~~~~~^
3 errors generated.
```
> Added missing #include to circular.h

- include/cinder/Stream.h
- include/freetype/config/ftoption.h
This adds a few missing `CI_API` statements and also allows access to the FreeType library when Cinder is compiled as a DLL.
Note: this used to be a branch on Cinder's repo, but it was better to create a PR instead,
> Fix DLL export for loadFileStream et. al. + FreeType

- include/cinder/app/KeyEvent.h
- samples/TextBox/src/TextBoxApp.cpp
- src/cinder/app/linux/AppImplLinuxGlfw.cpp
This is an initial implementation of unicode text input on linux / GLFW platforms. It requires storing an extra `ci::app::KeyEvent` to combine GLFW's `glfwSetKeyCallback` with the `glfwSetCharCallback`, but we discussed and thought this was the most flexible approach. Please let me know what you think, and if you write in a language that requires unicode support then testing is very welcome. :)
I've added a little code to the TextBox sample, and some logging that shows what's going on, which I'll remove before merging.
Fixes #1661
> Linux unicode input

- samples/QuaternionAccum/src/QuaternionAccumApp.cpp
Simple fix (typo in include statement)  that prevented the compilation of the QuaternionAccumApp sample.
> Fixed typo in header include

- include/cinder/Camera.h
- src/cinder/Camera.cpp
In an ortho box, the area of the near and far sides are the same. I needed to override the getFarClipCoorinates to not use the 'ratio' factor
> Fixing far plane coordinates for CameraOrtho

- include/cinder/app/AppBase.h
- src/cinder/app/AppBase.cpp
Consider this more as a suggestion -- needs more testing.
This is an alternative to the global app try-catch. Debuggers and crash dumps can often point to catch re-throw and hide the exact source of an exception. This would be prevented with this approach, while preserving the error logging.
Thoughts?
> Terminate handler instead of global try-catch

- proj/cmake/platform_macosx.cmake
This seems to be a residual from the recent Boost dependency removal that got missed on macOS and currently breaks compilation through CMake.
Tested on macOS 10.13.6 with Clang 9.0.0 and Cinder's current `master` branch.
> Remove boost artifacts from macOS cmake configuration.

- include/cinder/gl/Sync.h
Here's another example:
https://github.com/google/angle/blob/master/src/tests/gl_tests/FenceSyncTests.cpp#L257
> Prevent clientWaitSync to timeout immediately with default argument.

- src/cinder/Stream.cpp
- src/cinder/UrlImplWinInet.cpp
For some reason std::min and std::max couldn't be found without the inclusion of `<algorithm>` when building on windows via cmake
> Added missing <algorithm> header includes 

- include/cinder/gl/scoped.h
Allows users to directly set the desired matrices.
Old:
```
gl::ScopedMatrices scpMatrices;
gl::setMatrices( mCam );
gl::ScopedModelMatrix scpModel;
gl::setModelMatrix( mModelMatrix );
```
New:
```
gl::ScopedMatrices scpMatrices( mCam );
gl::ScopedModelMatrix scpModel( mModelMatrix );
```
> Added convenience constructors to Scoped*Matrix classes.

- src/imgui/imgui.cpp
Cherry-pick fix eefae082617cd36d9b1d412e481a7913ab0ef3f2 from dear imgui: Fixed clicking on void from not clearing focused window.
> Dear ImGui v1.77 cherry-picked hotfix for correcting ci::KeyEvent triggers.

- proj/cmake/platform_msw.cmake
- src/videoInput/videoInput.cpp
When compiling cinder using CMake on Windows, videoInput.cpp was missing from platform_msw.cmake, leading to unresolved external symbol errors. This commit adds videoInput.cpp back into the project and adds a cinder/video/msw source group to bring it in line with the cinder/audio/msw source group.
Tested using CMake 3.13.0, MSVC 15.8.8, Windows 10 build 1803.
> Added videoInput.cpp to msw platform cmake file and fixed header path

- proj/cmake/libcinder_target.cmake
- proj/cmake/platform_msw.cmake
Based on  MSVC version, the right toolset and compiler options are extracted and CXX_FLAGS are written. Solved a massive headache with VS 2019 not defaulting to c++17.
Also by adding `videoInput.cpp` to the cmake definition for Windows and setting the proper include path for it, CaptureBasic sample builds fine.
> Cmake update :: Visual Studio 2019 + videoInput

- proj/cmake/configure.cmake
The trailing slash is causing a double slash in my ```cinderConfig.cmake``` and subsequent cmake failures for apps. Removing the trailing slash seems to solve the issue and is also more in line with general policy to **not** add trailing slashes to cmake path variables.
If this is really a bug I'm a bit surprised because this doesn't look like it's a recent change and I'd expect it to have been causing a lot of issues.
Tested using:
* OSX 10.15.5
* CMAKE version 3.17.3
> Remove trailing slash from CINDER_LIB_DIRECTORY

- blocks/OSC/src/cinder/osc/Osc.cpp
- replaced remove_if() with find_if(), because removing an unique_ptr
from a vector causes it to become null, causing a crash later when
we try to dereference it.
> osc: fix crash when closing TCP receiver connections

- .travis.yml
- tools/linux/scripts/trusty-install-deps.sh
The oldest ubuntu distro, compiler and c++ standard and cmake version supported by cinder have changed quite a bit. 
Also travis itself has changed the environments it provides and what options are available. 
This PR cleans up the travis-ci file and tests cinder only with the default g++ and clang++ compiler on ubuntu bionic and focal respectively.
The main goal here is to make the ci-results usable again for development. Extending the test matrix to more compilers and more standard settings is left for a future PR.
> [CI] Update travis CI to use only supported ubuntu images

- blocks/OSC/src/cinder/osc/Osc.cpp
- blocks/OSC/src/cinder/osc/Osc.h
- test/unit/src/RandTest.cpp
- these were particularly verbose on Windows, mainly related to possible loss of data during size conversions (`size_t` to `int32_t` or `uint32_t`).
- there are still a few other warnings from ASIO, but fixing those may require replacing/updating the ASIO library.
I also added asserts (for extra safety/correctness), but if you don't like those they can be removed. We can "probably" assume no one will try to send OSC messages, arguments or blobs that are more than 2GB or 4GB in size, but just in case... (-;
*(unrelated)* I also fixed a bug in the `Rand` unit test, where I assume it was intending to only run a performance test in Release builds, but was instead doing it in Debug (which took forever). At least on Windows, `DEBUG` wasn't defined in the project (although `_DEBUG` is) -- but …
> Get rid of most warnings when building OSC block

- src/cinder/CinderImGui.cpp
The way modifier key state was sent to ImGui seemed flaky (it failed on Windows in the right-shift case because of the issue I describe in #2193); there are already `KeyEvent` tests that work well to indicate which modifiers are down.
This fixes the issue with `InputText` (and `InputTextMultiline`) on Windows, and should also be valid for Mac (even if it doesn't specifically fix an issue there).
> ImGui: fix "stuck" right shift key in InputText on Windows (#2193)

- test/unit/src/TestMain.cpp
The test app is created via ci_make_app, which
creates a win32 application instead of a simple console app.
This requires a WinMain entry point instead of the main
provided by catch.
> [UnitTests] Fix unit tests with cmake and msvc

- include/cinder/CinderImGui.h
- src/cinder/CinderImGui.cpp
Ran into this when updating some code that used Simon's Cinder-ImGui block to the built in imgui wrapper. Old method [here](https://github.com/simongeilfus/Cinder-ImGui/blob/29f75867c8646599e2df7584f396a215aeaa4102/include/CinderImGui.h#L258), and it is also natively supported using `ImGui::PushID( void * )`.
> added ScopedId( const void *ptrId )

- proj/cmake/modules/cinderMakeApp.cmake
- CINDER_PATH should  be ARG_CINDER_PATH (argument passed to function instead of global variable)
- No apparent reason, why policy CMP0015 should be set to old.
Remove this to silince cmake warnings about using outdated policies.
> [CMake] Fix setting msvc link directories in make app

- include/cinder/app/AppBase.h
std::result_of is deprecated in C++17 and removed in C++20, breaking downstream projects that use C++20 with MSVC
This could be replaced by a wrapper type trait that dispatches to std::invoke_result_t for C++17 and later or to std::result_of for
earlier versions but since it is only used in one place for nullary functors, decltype will be simpler.
The vendored version of boost::asio uses std::result_of so this PR will not allow Cinder to be built in C++20 mode yet, but since asio is only used internally and not in Cinder's interface it should allow downstream project to use C++20.
Fixes #2206
> Replace std::result_of with decltype

- include/cinder/ConcurrentCircularBuffer.h
- include/circular/circular.h
• Adding `uncancel()` and `clear()` methods
• Addressing some allocator-related warnings in C++17
> small ConcurrentCircularBuffer updates

- src/zlib/gzguts.h
Current master fails to build with the following error in macOS 10.15 with CMake and XCode 12.4 (12D4e).
The pull request contains the missing include file.
```
Building C object CMakeFiles/cinder.dir/src/zlib/gzlib.c.o
.../cinder/src/zlib/gzlib.c:252:9: fatal error: implicit
declaration of function 'lseek' is invalid in C99
[-Wimplicit-function-declaration]
LSEEK(state->fd, 0, SEEK_END);  /* so gzoffset() is correct */
^
.../cinder/src/zlib/gzlib.c:14:17: note: expanded from macro
'LSEEK'
^
.../cinder/src/zlib/gzlib.c:252:9: note: did you mean 'fseek'?
.../cinder/src/zlib/gzlib.c:14:17: note: expanded from macro
'LSEEK'
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include/stdio.h:162:6: note:
'fseek' declared here
int …
```
> Fixed zlib build error on macOS

- src/cinder/app/linux/PlatformLinux.cpp
added `#include <array>` in `src/cinder/app/Linux/PlatformLinux.cpp`
LLVM's libc++ requires that this be included to compile. I tested this on a Linux machine.
The reason for this is src/cinder/app/Linux/PlatformLinux.cpp:496, where an std::array is used. On stdlibc++, it seems that std::array is somehow included already in one of the standard headers; not so on libc++.
> portability with llvm's libc++ on Linux

- src/cinder/CinderImGui.cpp
- two calls to `toPixels()` were using the default `App` version (which
uses the "current" Window to do the conversion), but the current
Window is indeterministic when in an `update` handler, so with
multiple windows, it is likely to reference the wrong one.
- fixes Cinder issue #2241.
> Fix glitches when using ImGui in an app with multiple windows

- src/cinder/CinderImGui.cpp
Just adding the rest of the fixes I'd suggested earlier. They aren't strictly "necessary" (since the current window seems to be correct when the event and resize callbacks are called), but are cleaner and more consistent.
> Make ImGui multi-window more robust; fix issues noted in #2242

- proj/cmake/modules/cinderMakeApp.cmake
Otherwise, target_link_libraries cannot later be called with PUBLIC/PRIVATE/etc, and you get a cmake error if you try:
```
CMake Error at samples/_tutorials/Tutorial01_HelloTriangle/CMakeLists.txt:27 (target_link_libraries):
The plain signature for target_link_libraries has already been used with
the target "Tutorial01_HelloTriangle".  All uses of target_link_libraries
with a target must be either all-keyword or all-plain.
The uses of the plain signature are here:
* G:/code/cinder/cinder-main/proj/cmake/modules/cinderMakeApp.cmake:136 (target_link_libraries)
```
Apologies if this is somewhere already in one of the existing PRs / issues found in the nice list on #2189, I needed to make this change for a specific integration of cinder with a different library using cmake and the change is …
> ci_make_app: specify target_link_libraries with PUBLIC keyword

- src/cinder/app/AppScreenSaver.cpp
- src/cinder/app/cocoa/AppImplMacScreenSaver.mm
This commit fixes an error preventing new screensaver projects from rendering on MacOS.
It implements a solution found by athens and shared in [this forum post](https://discourse.libcinder.org/t/screensaver-on-osx-just-black-screen/1686/4).
> Fix to Screensaver on MacOS

- src/cinder/gl/Texture.cpp
The `channelOrder` parameter in ImageTargetGlTexture::create and constructor is used to set a value in the base class and not as an output variable. Having it as a pass by reference param is a bit confusing since it doesn't actually return a value.
> Removed unnecessary pass by reference for ImageTargetGlTexture channelOrder param

- include/cinder/Camera.h
- src/cinder/Camera.cpp
- add method dirtyViewCaches() to dirty both viewing and inverse
viewing matrix caches whenever the camera transform is modified.
Fixes bug #2238.
> Fix inverse viewing matrix caching bug in Camera class

- include/cinder/GeomIo.h
- samples/Geometry/assets/phong.frag
- samples/Geometry/src/GeometryApp.cpp
- src/cinder/GeomIo.cpp
… which creates a sphere primitive by normalizing the faces of a cube. Optionally, you can adjust the distribution of the vertices for a more pleasant look using `CubeSphere().equalSpacing()`. The Geometry sample has been updated to include this new primitive.
See also: https://youtu.be/sLqXFF8mlEU?t=97
EU
> Added a `geom::CubeSphere` class,… 

- src/cinder/Surface.cpp
The constant for src should be 3 instead of 4 since the src surface is
Rgb and not Rgba.
> Fixes copyRawRgbFullAlpha incorrect src offset

- src/cinder/msw/CinderMsw.cpp
- an error would be thrown when trying to log a message to the
console that was of length 1113 bytes.
- fixes issue #2272.
> Fix mysterious console logging crash

- .gitmodules
If you pull a fresh copy of cinder, Submodules will no longer download as the git: protocol is no longer supported. This chages the  protocol used to https. You may need to do a `git submodule sync` to update the submodules.
> Update protocol on submodules

- src/cinder/CinderImGui.cpp
As mentioned in https://github.com/cinder/Cinder/issues/2236 the app draw function is not guarantied to be called only once for each call to the update function. And as explained [here](https://github.com/ocornut/imgui/blob/master/imgui_internal.h#L2476) it is illegal to call ImGui functions after `ImGui::EndFrame()/ImGui::Render()`. Failing to do so will trigger or an assert or crash the app. I believe the `NewFrameGuard` was slightly changed when adapted from `Cinder-ImGui` and is now missing a check before the app emits its draw calls.
This means that currently it is only safe to use ImGui inside the scope of the update function.
This can be easily reproduced on Windows by adding a `ImGui::Text( "WillCrash" )` in the app draw method and dragging the window to the corner of the screen.
> Fixes DearImGui crash when the App issues more than one draw per update

- src/cinder/ImageIo.cpp
This fixes an issue in an atypical code path that would lead to an `ImageTarget` having an unmodified alpha channel if loading an `ImageSource` that has no alpha. The more expected behavior occurs now, which is that the alpha of the target is set to `max()` e.g. 255 for an 8bit image.
> ImageIo alpha issue

- blocks/OSC/src/cinder/osc/Osc.cpp
- blocks/OSC/src/cinder/osc/Osc.h
I use `removeAllListeners()` when doing complete re-initializations, and `getListeners()` for showing clients in the GUI.
> OSC: added methods for removing all listeners and getting all listeners.

- include/cinder/CinderImGui.h
- proj/cmake/libcinder_configure.cmake
- proj/cmake/libcinder_source_files.cmake
- src/cinder/CinderImGui.cpp
This PR allows to ship _Cinder_ along with an external version of _DearImGui_. 
It's great to have a script to update the version cinder is shipping with but it's a far less convenient solution when trying to setup a repository with a custom version of imgui. When working with a team it is easier to rely on submodules and cmake than having to depend on users to execute a python script.
The cmake changes are minimal but there's a couple of small required changes on the cpp side. Mostly the addition of a new `CINDER_IMGUI_EXTERNAL` preprocessor define to switch between the cinder friendly `#include "imgui/imgui.h"` and the standard `#include "imgui` used by _DearImGui_ (and all libraries built upon _DearImGui_). This is taken care of by appending to the `CINDER_DEFINES` cmake variable.
This …
> Added optional ${CINDER_IMGUI_DIR} cmake variable to build with an external version of ImGui

- include/cinder/Color.h
`ColorA( vec4 )` already exists, the analog was missing for 3-channel `ColorT` class. After this change, code like the following works:
```cpp
vec3 col = { 1, 0, 0 };
ci::Color boneColor = col;
```
Some of my code gets shared with GLSL, so it's nice in some cases to use `vec3` instead as an RGB color like you do in shaders, but then for other that use `ci::Color`, seemlessly convert to what you need. Without, you must do:
```cpp
vec3 col = { 1, 0, 0 };
ci::Color boneColor( col.x, col.y, col.z );
// or:
ci::Color boneColor = {  col.x, col.y, col.z };
```
However as I first noted, [there is already a constructor](https://github.com/cinder/Cinder/blob/e10faebb9750a74b16ac772e122c59b260dbf003/include/cinder/Color.h#L197-L200) for the 4-channel version that allows for this:
```cpp
vec4 col = { …
```
> Add missing ci::Color( vec3 ) overload.

- src/cinder/Font.cpp
* Outlines were hinted, causing deformations to the actual clean outline. Outlines are now unhinted.
This is the letter `X` of the Arial font with hinting enabled:
Here is the same letter, but with hinting disabled:
* Quadratic curves were converted to cubic curves. This unnecessarily increases complexity of the outlines and introduces extra vertices. If triangulated, these extra vertices cause extra triangles, etc. There is no need to convert quadratic curves, as they are natively supported by the Path2d class.
This is the letter `e` of the Arial font triangulated after extracting the outline using the old version, which converts quadratic curves to cubic curves, resulting in this case in 70 triangles:
Here is the same letter, but using the quadratic curves defined by the font, leading …
> Fix for font outlines. See below:

- include/cinder/TriMesh.h
- src/cinder/TriMesh.cpp
- src/cinder/gl/VboMesh.cpp
This PR:
* Completes support for `geom::BONE_INDEX` and `geom::BONE_WEIGHT` to `TriMesh`. It currently assumes that bone indices are limited to 4 bones, and that they are stored in floating point values rather than integers. Adding support for integer-based bone indices will require changes to a lot of the internal `geom` machinery and can be worked around for now. We'll plan to revisit this at some point in the future however.
* Previously `TriMesh` and `gl::VboMesh` ignored the `strideBytes` parameter on copyAttrib when they were being loaded through a `geom::Target`. This is now fixed.
> Bones + TriMesh/VboMesh fixes (redux)

- include/cinder/Path2d.h
- include/cinder/Shape2d.h
- src/cinder/Path2d.cpp
- src/cinder/Shape2d.cpp
In preparation of path rendering, these additions will make it much easier to define paths and shapes from code.
> Path2d and Shape2d additions: basic shapes and commands.

- src/cinder/audio/Param.cpp
Increment iterator in the cases where the current node is not
removed from the list.
> Missing iterator increment

- include/cinder/Utilities.h
- src/cinder/Utilities.cpp
- src/cinder/app/Platform.cpp
This PR adds two new functions, `findAncestorFile()` and `findAncesorDir()`. These are utility functions for locating a relative path somewhere up the disk hierarchy from another path.
A good example is how Cinder automatically locates the _assets_ directory relative to the application, and in fact this PR reimplements that functionality to use `findAncestorDir()` internally. Also useful for a scenario where you have an external resource like an .exe dependency. An example call would be `auto toolPath = findAncestorFile( getAppPath(), "external\\tools\\example.exe" )`
> findAncestor* path

- proj/cmake/modules/FindMPG123.cmake
Platform : Ubuntu 24.04 LTS
I installed dependencies found here https://libcinder.org/docs/guides/linux-notes/ubuntu.html
I faced this error:
```
CMake Error at /usr/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
Could NOT find MPG123 (missing: MPG123_INCLUDE_DIR)
Call Stack (most recent call first):
/usr/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
proj/cmake/modules/FindMPG123.cmake:35 (find_package_handle_standard_args)
proj/cmake/platform_linux.cmake:143 (find_package)
CMakeLists.txt:29 (include)
```
Here is a fix i found
> Fix Could NOT find MPG123 on Ubuntu 24.04 LTS

- .github/workflows/xcode-macOS.yml
The previous macos-11 has been removed
> Update xcode-macOS.yml to `macos-13` runner

- include/glad/glad.h
This is an alternative to my PR #2332, which didn't actually solve the problem with these GLAD warnings with MSVC, and not as "heavy" as updating to GLAD 2:
```
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.20348.0\shared\minwindef.h(130,1): warning C4005: 'APIENTRY': macro redefinition
1>(compiling source file '../../src/cinder/gl/wrapper.cpp')
1>C:\Users\holag\Documents\Work\...\cinder\include\glad\glad.h(518,1):
1>see previous definition of 'APIENTRY'
```
This happens when building with MSVC, depending on the include order of GLAD headers vs Windows headers that define `APIENTRY`. Adding the push/pop seems like a simple solution to the problem.
> Fix Windows warnings about APIENTRY from GLAD library

- src/cinder/CinderImGui.cpp
Update mouse event handlers in CinderImGui to set modifier key states (KeyCtrl, KeyShift, KeyAlt, KeySuper) from MouseEvent. Previously these were only set during keyboard events, causing ImGui features like Ctrl+Click on sliders to not work reliably on Linux.
The fix ensures modifier states are synchronized with ImGui during all mouse events (MouseDown, MouseUp, MouseMove, MouseDrag, MouseWheel).
> Fix ImGui Ctrl+Click functionality on Linux

- .github/workflows/cmake-ubuntu.yml
- Replace external script call with direct apt-get commands
- Add missing libunwind-dev dependency for gstreamer
> Inline dependency installation in Ubuntu workflow

- include/cinder/CanvasUi.h
- include/cinder/app/MouseEvent.h
- proj/cmake/libcinder_source_files.cmake
- proj/vc2019/cinder.vcxproj
- proj/xcode/cinder.xcodeproj/project.pbxproj
- samples/CanvasUi/include/Resources.h
- samples/CanvasUi/proj/cmake/CMakeLists.txt
- samples/CanvasUi/proj/vc2019/CanvasUi.sln
- samples/CanvasUi/proj/vc2019/CanvasUi.vcxproj
- samples/CanvasUi/proj/vc2019/CanvasUi.vcxproj.filters
- samples/CanvasUi/proj/vc2019/Resources.rc
- samples/CanvasUi/proj/xcode/CanvasUi.xcodeproj/project.pbxproj
- samples/CanvasUi/proj/xcode/CanvasUi_Prefix.pch
- samples/CanvasUi/proj/xcode/Info.plist
- samples/CanvasUi/src/CanvasUiApp.cpp
- samples/CanvasUiMinimap/include/Resources.h
- samples/CanvasUiMinimap/proj/cmake/CMakeLists.txt
- samples/CanvasUiMinimap/proj/vc2019/CanvasUiMinimap.sln
- samples/CanvasUiMinimap/proj/vc2019/CanvasUiMinimap.vcxproj
- samples/CanvasUiMinimap/proj/vc2019/CanvasUiMinimap.vcxproj.filters
- samples/CanvasUiMinimap/proj/vc2019/Resources.rc
- samples/CanvasUiMinimap/proj/xcode/CanvasUiMinimap.xcodeproj/project.pbxproj
- samples/CanvasUiMinimap/proj/xcode/CanvasUiMinimap_Prefix.pch
- samples/CanvasUiMinimap/proj/xcode/Info.plist
- samples/CanvasUiMinimap/src/CanvasUiMinimapApp.cpp
- src/cinder/CanvasUi.cpp
This is a continuation of work @paulhoux started with PR #2326, implementing a `CanvasUi` class, similar to `CameraUi` but for 2D canvas manipulation.
This PR includes two samples, one exercising most of the functionality, _CanvasUi_, and another showing how to implement a mini-map paired with `CanvasUi` called _CanvasUiMinimap_.
The implementation allows customization of hotkeys and mouse interactions, but by default uses middle, right, or alt-left clicking for panning, leaving left click for selecting. It also supports several hotkeys for zoom by default.
One key concept is the notion of a bounded vs. unbounded canvas. The former is required for "fitting" functionality, which allows automatic zoom to fit height, width, etc to the window. An unbounded canvas cannot be fit to a window but …
> CanvasUi implementation

- include/cinder/Signals.h
- src/cinder/Signals.cpp
This will allow `std::vector<Connection>` and `std::vector<ScopedConnection>` to resize a little more efficiently. Was only waiting until our minimum compiler on MSW was v140 which is now the case.
Fixes #1681. That issue is marked for 0.9.2 milestone, although this is a pretty minor modification so it can be merged before or after that lands.
> Added noexcept to signals move constructors and assignment operators.

- include/cinder/CinderImGui.h
- src/cinder/CinderImGui.cpp
The `power` parameter was removed from DragFloat/SliderFloat functions in ImGui 1.78
and replaced with `ImGuiSliderFlags` (see ocornut/imgui#3361).
Updated CinderImGui wrapper functions to use the new API:
- DragFloat2/3/4: changed `float power = 1.0f` → `ImGuiSliderFlags flags = 0`
- SliderFloat2/3/4: changed `float power = 1.0f` → `ImGuiSliderFlags flags = 0`
Users needing non-linear behavior can now pass `ImGuiSliderFlags_Logarithmic` instead.
> Fix Removed power param in imgui

- proj/cmake/libcinder_configure.cmake
- proj/cmake/libcinder_source_files.cmake
- proj/cmake/libcinder_target.cmake
- proj/cmake/platform_macosx.cmake
- proj/cmake/platform_msw.cmake
- proj/vc2019/cinder.vcxproj
- proj/vc2019/cinder.vcxproj.filters
This PR updates the mechanism for C++17 standard enforcement with CMake, and brings parity on macOS and Windows to their respective platform-specific build files.
- Replaces manual compiler flag detection with `target_compile_features(cxx_std_17)`
- Sets `CXX_STANDARD 17`, `CXX_STANDARD_REQUIRED ON`, and `CXX_EXTENSIONS OFF` via `set_target_properties()`
- Removes brittle manual `-std=c++17` flag logic that broke downstream compilation with tools like nvcc
- Ensures `-std=c++17` is applied instead of GNU extensions mode, preventing the `linux` macro from conflicting with `namespace linux` in system headers
- Updates minimum MSVC requirement to Visual Studio 2019 (MSVC 19.20)
- Adds `HAVE_UNISTD_H` definition for non-Windows platforms
- Moves `Filesystem.cpp` to macOS-only builds (related …
> CMake C++17 Enforcement and Platform Parity Improvements

- src/cinder/app/linux/PlatformLinux.cpp
Fixes Linux file dialog paths containing trailing newline characters, which broke file operations.
The popen reading code incorrectly used `feof()` and set a null byte without resizing the string. Now uses standard `fgets()` pattern and `pop_back()` to properly remove the trailing newline.
> Fix Linux file dialog paths with trailing newline

- docs/htmlsrc/guides/dependencies/index.html
- include/cinder/ImageFileTinyExr.h
- include/tinyexr/tinyexr.h
- proj/cmake/libcinder_source_files.cmake
- proj/vc2019/cinder.vcxproj
- proj/vc2019/cinder.vcxproj.filters
- proj/xcode/cinder.xcodeproj/project.pbxproj
- src/cinder/ImageFileTinyExr.cpp
- src/tinyexr/tinyexr.cc
Updates TinyEXR from 0.9.5 to 1.0.12. The new version is header-only, which simplifies the build system. Also adds detection for unsupported EXR format types and changes default compression to ZIP.
https://github.com/syoyo/tinyexr/releases/tag/v1.0.12
> Update TinyEXR to 1.0.12
