include/cinder/MayaCamUI.h
Panning behaves correctly regardless of camera orientation.
=> Panning behaves correctly regardless of camera orientation.

include/cinder/GeomIo.h, samples/Geometry/src/GeometryApp.cpp, src/cinder/GeomIo.cpp, src/cinder/gl/Context.cpp, src/cinder/gl/gl.cpp, test/_opengl/ConvenienceDrawingMethods/src/ConvenienceDrawingMethodsApp.cpp, test/_opengl/ConvenienceDrawingMethods/xcode_ios/ConvenienceDrawingMethods.xcodeproj/project.pbxproj, test/_opengl/ConvenienceDrawingMethods/xcode_ios/ConvenienceDrawingMethods_Prefix.pch
Under-the-hood updates to geom to accelerate gl::draw(Source) and gl::draw(VboMesh)
=> Gl next draw source

include/cinder/gl/Batch.h, include/cinder/gl/VboMesh.h, include/cinder/gl/draw.h, src/cinder/gl/Batch.cpp, src/cinder/gl/VboMesh.cpp, src/cinder/gl/draw.cpp
=> ranged methods for drawing gl::Batch and gl::VboMesh

samples/Compass/src/CompassApp.cpp, samples/MotionBasic/src/MotionBasicApp.cpp
=> Compass sample updates for latest glNext

test/_opengl/PboUploadTest/src/PboUploadTestApp.cpp, test/_opengl/PboUploadTest/xcode/PboUploadTest.xcodeproj/project.pbxproj
Source changes needed to compile.
Project changes needed to link.
=> Update PBO test to work with latest glNext.

include/cinder/params/Params.h, src/cinder/params/Params.cpp
Added enumerated parameters with accessors for partly solving #444. Please revise.
=> enumerated parameters with callbacks

src/cinder/gl/draw.cpp
=> added case for closed polyLine in draw

src/cinder/GeomIo.cpp, src/cinder/TriMesh.cpp
Addresses https://github.com/cinder/Cinder/issues/829
=> TriMesh from TRIANGLE_STRIP/FAN primitives

src/cinder/gl/Context.cpp
Fix my previous bad commit and solves my [shameful monologue here.](https://github.com/cinder/Cinder/issues/856)
Sorry about that! : )
=> Added default/initial Depth test and func stack values

include/cinder/gl/Context.h, include/cinder/gl/scoped.h, include/cinder/gl/wrapper.h, src/cinder/gl/Context.cpp, src/cinder/gl/scoped.cpp, src/cinder/gl/wrapper.cpp
I added functionality for glLogicOp.
I'm not sure about the naming of the different functions - let me know if you have better naming ideas.
=> glNext - Added glLogicOp functionality.

src/cinder/gl/ConstantConversions.cpp, src/cinder/gl/GlslProg.cpp, src/cinder/gl/VboMesh.cpp
- Added GL_SAMPLER_RECT to GlslProg and ConstantConversions, 
- Also fixed logic for ignoring warnings related to logging gl_InstanceID and gl_VertexID Attributes
=> GlslProg Type additions and VboMesh fixes

src/cinder/ip/EdgeDetect.cpp
Potential fix for https://github.com/cinder/Cinder/issues/899
=> Potential Fix for ip::EdgeDetect and Surface32f/Channel32f

include/cinder/app/RendererGl.h, samples/_opengl/Cube/src/CubeApp.cpp, samples/_opengl/CubeMapping/src/CubeMappingApp.cpp, samples/_opengl/DynamicCubeMapping/src/DynamicCubeMappingApp.cpp, samples/_opengl/MipMap/src/MipMapApp.cpp, samples/_opengl/MotionBlurVelocityBuffer/src/MotionBlurVelocityBufferApp.cpp, samples/_opengl/NormalMapping/src/NormalMappingApp.cpp, samples/_opengl/ShadowMapping/src/ShadowMappingApp.cpp, samples/_opengl/StencilReflection/src/StencilReflectionApp.cpp, samples/_opengl/TessellationBezier/src/TessellationBezierApp.cpp, samples/_opengl/TransformFeedbackClothSimulation/src/TransformFeedbackClothSimulationApp.cpp, samples/_opengl/VboMesh/src/VboMeshApp.cpp
Follows from [this forum post](https://forum.libcinder.org/topic/cinder-multisampled-anti-aliasing-and-large-high-resolution-displays), and the email discussion. Are we still going for this? Should I go through more samples?
=> Disabled msaa by default

samples/_opengl/MotionBlurVelocityBuffer/assets/velocity.fs, samples/_opengl/MotionBlurVelocityBuffer/assets/velocity.vs
The cones looked a little flat, so I added simple directional lighting to it. Let me know if you have any objections.
Before:
After:
=> Added directional lighting to the motion blur sample.

include/cinder/Color.h, include/cinder/TriMesh.h, samples/Tubular/src/Tube.cpp, samples/_audio/DelayFeedback/src/DelayFeedbackApp.cpp, src/cinder/TriMesh.cpp, src/cinder/Triangulate.cpp
=> glNext TriMesh method name / return value improvements

samples/ImageFileBasic/xcode/ImageFileBasic.xcodeproj/project.pbxproj, src/cinder/app/cocoa/AppImplMac.mm, src/cinder/app/cocoa/CinderViewMac.mm, src/cinder/app/cocoa/PlatformCocoa.cpp, src/cinder/gl/Context.cpp, test/windowTest/src/windowTestApp.cpp, test/windowTest/xcode/windowTest.xcodeproj/project.pbxproj
Attempts to address fullscreen bug discussed on #960 by forcing the pre-fullscreen window to the back when app regains foreground, and after open/save dialog.
=> Fullscreen osx fix addressing #960

include/cinder/PolyLine.h
Makes debugging it much nicer. I'm totally open to suggestions on the formatting.
=> Add an output stream operation to PolyLine.

blocks/__AppTemplates/BasicApp/OpenGL/xcode/Info.plist, blocks/__AppTemplates/CocoaView/OpenGL/xcode/Info.plist, blocks/__AppTemplates/__Foundation/xcode/project.pbxproj, src/cinder/Clipboard.cpp, src/cinder/app/cocoa/AppImplMac.mm, src/cinder/app/cocoa/RendererImpl2dMacQuartz.mm, src/cinder/qtime/QuickTimeImplAvf.mm
A few bits and bobs found via the static analyzer and from creating a new app via TinderBox - if you'd prefer they were split up I can do that too, but they all seemed so small that it might be a bit of overkill.
=> OS X warnings, leaks and tweaks

samples/CaptureBasic/src/CaptureBasicApp.cpp, samples/_audio/BufferPlayer/src/BufferPlayerApp.cpp, samples/_audio/DelayFeedback/src/DelayFeedbackApp.cpp, samples/_audio/InputAnalyzer/src/InputAnalyzerApp.cpp, samples/_audio/InputAnalyzer/vc2013/InputAnalyzer.sln, samples/_audio/NodeAdvanced/src/NodeAdvancedApp.cpp, samples/_audio/NodeBasic/src/NodeBasicApp.cpp, samples/_audio/NodeSubclassing/src/CustomTremoloNode.h, samples/_audio/VoiceBasic/src/VoiceBasicApp.cpp, test/_audio/EffectsXAudioTest/src/EffectsXAudioTestApp.cpp
Added missing #included gl.h's and msaa where it was useful.
=> Win (mainly audio) sample updates

src/cinder/app/msw/RendererImplGlAngle.cpp
The existing display attributes require feature level 10.0+ and following [template code from the MSOpenTech/angle repo](https://github.com/MSOpenTech/angle/blob/ff68ed35a5fe07283e804849d56ae3993756faa4/templates/10/Windows/Windows%20Universal/XamlUniversal/OpenGLES.cpp#L107-131), we can test for and support 9.3. A few proximate space <-> tabs were also fixed too. With this, I was able to build and run Cinder apps on a Windows 8.1 guest running in VMWare Fusion.
=> Add D3D11 feature level 9.3 support to ANGLE renderer

docs/doxygen/docsrc/guides/tour/chapter1.dox
libcinder.org should also be updated.
http://libcinder.org/docs/v0.8.6/hello_cinder_chapter1.html
=> fix link to Mac OS X project setup in Chapter 1 of Hello, Cinder 

samples/FallingGears/src/Box2dUtils.cpp, samples/FallingGears/src/FallingGearsApp.cpp, samples/FallingGears/src/SceneController.cpp, samples/FallingGears/src/SceneObjects.cpp, samples/FallingGears/src/SceneObjects.h, samples/_audio/MultichannelOutput/src/MultichannelOutputApp.cpp, samples/_audio/NodeAdvanced/src/NodeAdvancedApp.cpp, samples/_audio/NodeSubclassing/src/NodeSubclassingApp.cpp, samples/_audio/VoiceBasicProcessing/vc2013/VoiceBasicProcessing.vcxproj
Updates for glnext changes, build fixes, and using `gl::Batch` in favor of `gl::draw( Path2d )` as it is a big performance gain.
=> FallingGears sample updates

test/DebugTest/vc2013/Resources.rc, test/DebugTest/xcode/DebugTest.xcodeproj/project.pbxproj
Using the icons available in samples/data rather than files in the local project.
=> Properly referencing samples/data for the project icons

include/cinder/audio/Buffer.h, include/oggvorbis/ogg/config_types.h, src/cinder/audio/OutputNode.cpp, src/cinder/audio/Utilities.cpp, src/cinder/audio/cocoa/ContextAudioUnit.cpp, src/cinder/audio/msw/ContextWasapi.cpp, src/cinder/audio/msw/ContextXAudio.cpp, src/oggvorbis/readme.txt, test/eventTest/xcode/eventTest.xcodeproj/project.pbxproj
A couple things needed to build ci::audio /w gcc for android but were otherwise general, some variable name fixing and updating eventTest to build with master.
=> Audio maintenance

include/cinder/gl/Fbo.h, src/cinder/gl/Fbo.cpp
I chose not to use a reference to a shared_ptr, as we want to make sure to Fbo remains valid while blitting.
=> Changed parameter for Fbo::blitTo from Fbo to FboRef.

include/cinder/CinderAssert.h, include/cinder/audio/Context.h, src/cinder/audio/Context.cpp
Found these looking around, no functional changes.
=> Small comment update and a spelling error in audio code.

samples/Kaleidoscope/src/InstascopeApp.cpp, samples/Kaleidoscope/src/TextRibbon.cpp, samples/Kaleidoscope/src/TrianglePiece.cpp
So, Rich, well... I won't be spending the time to reproduce these exact visuals in Glsl I'm afraid. These updates suffice.
If anyone has some free time to lose, here it is: https://www.shadertoy.com/view/ltl3WN
=> Kaleido sample update

samples/Geometry/assets/phong.frag, samples/Geometry/src/GeometryApp.cpp
* Fixed a seam in Icosphere by setting texture wrap to GL_REPEAT (as it should be).
* Added a FileDrop event to allow users to drag-and-drop their texture onto the primitive.
* Moved brown color to the shader, otherwise it would affect the custom texture.
=> Fixed the Geometry sample.

include/cinder/Log.h, samples/Logging/include/Resources.h, samples/Logging/src/LoggingApp.cpp, samples/Logging/vc2013/Logging.sln, samples/Logging/vc2013/Logging.vcxproj, samples/Logging/vc2013/Logging.vcxproj.filters, samples/Logging/vc2013/Resources.rc, samples/Logging/xcode/Info.plist, samples/Logging/xcode/Logging.xcodeproj/project.pbxproj, samples/Logging/xcode/Logging_Prefix.pch, src/cinder/Log.cpp, test/DebugTest/src/DebugTestApp.cpp
Added a simple logging sample app.  Some colleagues I had spoken with didn't instinctively know where to look for logging examples, and I think it makes sense to have a straight forward example available for users.
=> Adding Logging sample app

include/cinder/Log.h, samples/Logging/src/LoggingApp.cpp, src/cinder/Log.cpp
=> Logger restructure2

test/DebugTest/src/DebugTestApp.cpp
Changed DebugTest to reflect changes from #1130
=> Logging DebugTest update

docs/htmlsrc/reference/audio.html, include/cinder/audio/dsp/Converter.h
And fixed a typo in inline docs.
=> Improve audio reference

docs/htmlsrc/_assets/css/style.css, docs/htmlsrc/_assets/js/cinder.js, docs/htmlsrc/index.html
Fixes this code copy bug https://github.com/cinder/Cinder/issues/1154
=> Dox next fixes

include/cinder/gl/Ubo.h
So that platform.h is included before we check.
=> Move define check after header include

include/cinder/Arcball.h, include/cinder/CameraUi.h, src/cinder/CameraUi.cpp, test/FloatCamera/src/FloatCameraApp.cpp, test/FloatCamera/vc2013/FloatCamera.sln, test/FloatCamera/vc2013/FloatCamera.vcxproj, test/FloatCamera/vc2013/FloatCamera.vcxproj.filters, test/FloatCamera/vc2013/Resources.rc, test/FloatCamera/xcode/FloatCamera.xcodeproj/project.pbxproj, test/FloatCamera/xcode/FloatCamera_Prefix.pch, test/FloatCamera/xcode/Info.plist
=> changed Arcball and CameraUi to take float vectors

include/cinder/Sphere.h, include/cinder/gl/draw.h, src/cinder/Sphere.cpp, src/cinder/gl/draw.cpp
Also added a convenience method to render the sphere.
=> Additional ray-sphere intersection code, similar to AxisAlignedBox.

include/cinder/GeomIo.h, src/cinder/GeomIo.cpp
Also fixed a few minor issues with some of the primitives.
=> Added a TorusKnot primitive.

src/cinder/app/msw/AppImplMsw.cpp, src/cinder/app/msw/RendererImplGlMsw.cpp
See this post: https://forum.libcinder.org/#Topic/23286000002474049
=> Fix for issue #1172, as reported and proposed by SteveH.

docs/htmlsrc/guides/cinder-blocks/index.html
=> Update TinderBox link

docs/htmlsrc/guides/logging/index.html
Finally finished the logging guide.  Let us all bask in its glory.
=> Added logging guide

docs/htmlsrc/_docs/log/Logger.html
Added some supplementary html for the LoggerFile and LoggerFileRotating classes
=> Added supplementary html for LoggerFile and LoggerFileRotating

docs/generateDocs.py, docs/htmlsrc/_assets/css/style.css, docs/stylesrc/stylus/cinder_docs.styl
=> Fixed code syntax within function descriptions

CONTRIBUTING.md
Added guide info for `if()` body on new line, comment after closing namespace bracket, fixed up example code.
=> Styleguide updates

samples/Geometry/assets/phong.frag, samples/Geometry/src/GeometryApp.cpp
* Added support for Torus Knot.
* Each primitive can now have its own tweakable parameters.
* Camera recenter now maintains view direction.
* Camera recenter uses fixed timestep.
=> Updated Geometry sample.

docs/htmlsrc/guides/audio/index.html, include/cinder/audio/InputNode.h
Removed stray code block in guide and fixed a doxygen line.
=> Audio doc cleanup

test/unit/.gitignore, test/unit/src/JsonTest.cpp, test/unit/src/signals/SignalsTest.cpp, test/unit/vc2013/unit.sln, test/unit/vc2013/unit.vcxproj, test/unit/vc2013/unit.vcxproj.filters
Adding Visual Studio 2013 build files for unittests per Rich's request and making (hopefully) minor changes to existing tests for cross-platform and vs friendliness
=> vc2013 build files for unit tests

include/cinder/Log.h, test/DebugTest/src/DebugTestApp.cpp
Part of me wants to call it ```makeOrGetLogger``` but I acknowledge that it's a little long.
This is in reference to #1265
=> added makeOrGet helper function

src/cinder/GeomIo.cpp
Thanks to @Hurleyworks and @gaborpapp for their investigation.
=> Fix for issue 1251. 

docs/generateDocs.py
=> Logs an error if tag file is missing.

docs/htmlsrc/_assets/js/cinder.js
Fixes issue mentioned in #1245.
=> Docs search result root directory is determined correctly.

blocks/OSC/src/Osc.cpp, blocks/OSC/src/Osc.h
Fixes #1308 
Tested on Windows.
=> Set mIsCached to false when the cache is empty

include/cinder/AxisAlignedBox.h, include/cinder/Sphere.h, src/cinder/Sphere.cpp
I needed this for an upcoming project and noticed it wasn't in Cinder yet. Based in part on: 
http://www.realtimerendering.com/resources/GraphicsGems/gems/BoxSphere.c
=> Added fast aabb-sphere intersection test.

src/cinder/ObjLoader.cpp, test/unit/src/ObjLoaderTest.cpp
=> Perform line continuation logic in ObjLoader.

docs/htmlsrc/guides/docs/building_docs.html
After #1245 I had a thoughts on how we could improve the docs building guide.
=> Improve guide for building docs

src/cinder/app/linux/AppImplLinuxEgl.cpp
Referenced from [this](https://forum.libcinder.org/#Topic/23286000002634083) forum thread.
=> Add missing mouse down modifiers RPi2.

include/cinder/gl/Batch.h, src/cinder/gl/Batch.cpp
Reverts cinder/Cinder#1370 (until reviewed)
=> Revert "VertBatch cleanup"

include/cinder/gl/Batch.h, samples/_opengl/ImmediateMode/src/ImmediateModeApp.cpp, src/cinder/gl/Batch.cpp
This is the commit from #1370 to fix VertBatch on rasberry pi, which I prematurely merged.
=> Thyrrestrup vert batch cleanup

src/cinder/app/linux/PlatformLinux.cpp
Needed for the ObjLoader sample.
=> Implement ci::app::expandPath on Linux.

include/cinder/CameraUi.h, src/cinder/CameraUi.cpp
Storing them in a vector to make that easier.
=> Clear out existing CameraUi signals before connecting again

.gitignore
Appears after installing VS 2015 update 2.
=> Ignore Visual Studio's new DB file

include/cinder/gl/GlslProg.h
=> Fix typo in comment

blocks/__AppTemplates/CocoaView/OpenGL/include/_TBOX_PREFIX_App.h, blocks/__AppTemplates/CocoaView/OpenGL/include/_TBOX_PREFIX_Delegate.h, blocks/__AppTemplates/CocoaView/OpenGL/src/_TBOX_PREFIX_App.cpp, blocks/__AppTemplates/CocoaView/OpenGL/src/_TBOX_PREFIX_Delegate.mm, blocks/__AppTemplates/CocoaView/OpenGL/xcode/_TBOX_PREFIX__Prefix.pch, blocks/__AppTemplates/CocoaView/OpenGL/xcode/en.lproj/MainMenu.xib
Integrated changes from @kjhollen into the CocoaView OpenGL app template. Additionally changed the template to initialize the user application with a default renderer before it is instantiated.
Should fix issue #1073
=> updated CocoaView OpenGL app template so it builds and works with v0.9.0

CONTRIBUTING.md
=> Typo correction in contributing.md

docs/htmlsrc/_assets/js/cinder.js
Docs search result root directory is determined correctly. Fixes issues mentioned in #1245.
=> Docs search link 404 fix

proj/cmake/libcinder_target.cmake
Affects Ubuntu 14.04 in particular.
Added TODO for when we bump up min cmake version.
=> Reverting #1535 as it breaks on cmake < 3.3

src/cinder/Base64.cpp, test/unit/src/Base64Test.cpp
Fixes https://github.com/cinder/Cinder/issues/1554
=> Fix buffer overflow caught by valgrind

samples/_opengl/PostProcessingAA/assets/fxaa.frag, samples/_opengl/PostProcessingAA/src/fxaa/FXAA.cpp, samples/_opengl/PostProcessingAA/src/fxaa/FXAA.h, samples/_opengl/PostProcessingAA/src/smaa/SMAA.cpp, samples/_opengl/PostProcessingAA/src/smaa/SMAA.h
=> PostProcessAA sample: use Batch instead of slower gl::drawSolidRect()

proj/cmake/libcinder_source_files.cmake
=> Don't add glload files when building for OpenGL ES

src/cinder/app/AppBase.cpp
At this point we're we're going down, so message should be at the fatal level.
=> Log uncaught exception as fatal

include/cinder/gl/VboMesh.h, src/cinder/gl/VboMesh.cpp
- Added setters for num indices and vertices 
- changed logic for drawImpls to rely on the indices pointer rather than the number of indices
=> Updated VboMesh functionality to allow streaming.

src/cinder/GeomIo.cpp
=> Fix oversizing of geom::Sphere index buffer

include/cinder/ObjLoader.h
I noticed a couple of typos in the docs for these methods.
=> Fix some spelling

src/cinder/app/linux/AppImplLinuxGlfw.cpp
This adds scroll events to Linux Apps. 
Tested on Ubuntu 16.
=> Handle mouse wheel events for Linux

src/cinder/System.cpp
System::getNetworkAdapters() was getting stuck in an infinite loop with an active VPN connection on my machine. The problem was it was returning a nonzero value getting the subnet so we call continue but didn't advance to the next interface, so the failure just keeps repeating.
I fixed this by letting it fetch both values and then only adding it to the vector if both succeeded. 
The indenting changed a bit since there was a mix of tabs and spaces before. 
Fixes #1619
=> Avoid infinite loop if getnameinfo fails

blocks/OSC/proj/cmake/OSCConfig.cmake, blocks/TUIO/proj/cmake/TUIOConfig.cmake
Removed compile options as the parent app should provide these.
=> Block Cmake Config Change

src/cinder/app/linux/AppImplLinuxGlfw.cpp
- Added a modifiers function to extract intuitive character from glfw using native key code modifiers.
- Haven't yet addressed unicode keys. But this step is needed in the immediate.
=> Linux Key Code Modifiers

include/cinder/GeomIo.h, include/cinder/ImageIo.h, include/cinder/Timeline.h, include/cinder/Url.h, src/cinder/Clipboard.cpp, src/cinder/Font.cpp, src/cinder/GeomIo.cpp, src/cinder/ImageFileTinyExr.cpp, src/cinder/ImageSourceFileRadiance.cpp, src/cinder/ImageSourceFileStbImage.cpp, src/cinder/ImageSourcePng.cpp, src/cinder/Log.cpp, src/cinder/ObjLoader.cpp, src/cinder/Timeline.cpp, src/cinder/Triangulate.cpp
=> Comment more unused function parameters to prevent compiler warnings

include/cinder/app/AppScreenSaver.h, include/cinder/app/Renderer.h, include/cinder/app/msw/AppImplMswScreenSaver.h, include/cinder/app/msw/PlatformMsw.h, src/cinder/app/Renderer.cpp, src/cinder/app/msw/AppImplMsw.cpp, src/cinder/app/msw/AppImplMswScreenSaver.cpp, src/cinder/app/msw/PlatformMsw.cpp, src/cinder/app/msw/RendererImpl2dGdi.cpp, src/cinder/app/msw/RendererImplGlMsw.cpp
=> Comment unused function params in cinder/app

proj/vc2013/cinder.vcxproj, proj/vc2013/cinder.vcxproj.filters, proj/xcode/cinder.xcodeproj/project.pbxproj
- Added freetype to osx, ios, ios-sim projects
- Adding freetype to windows and winrt projects
=> Freetype Project Addition

include/cinder/app/linux/PlatformLinux.h, src/cinder/app/linux/PlatformLinux.cpp
- Adds needed functionality for caching and using `Display` on the Linux Platform.
=> Added Display functionality to Linux

src/cinder/Serial.cpp
Mainly refactoring `Serial::readStringUntil`. There is certainly more that could be done, but these are some low-hanging fruits.
=> Small simplifications to Serial.cpp

include/cinder/gl/GlslProg.h, src/cinder/gl/GlslProg.cpp
Made ```GlslProg::uniformBlock``` ```const``` and ```GlslProg::UniformBlock::mBlockBinding``` ```mutable```.
=> Made ```GlslProg::uniformBlock``` const

test/unit/proj/cmake/CMakeLists.txt, test/unit/src/JsonTest.cpp, test/unit/src/UnicodeTest.cpp, test/unit/vc2013/unit.vcxproj
Fixes #1666, and the Visual Studio project setup.
=> Unit test fixes for non-cmake platforms

.travis.yml, proj/xcode/fullbuild-xcpretty.sh, proj/xcode/iosbuild-xcpretty.sh, tools/ci/cmake_test.sh, tools/ci/xcode_test.sh
Added CI building and testing via the xcode project.
=> Travis ci via xcode

.travis.yml
This should make it easier to discern what is happening.
Example build [here](https://travis-ci.org/lucasvickers/Cinder/builds/185306850).
=> Added descriptions to travis environment

include/cinder/app/linux/AppImplLinux.h, src/cinder/app/linux/AppImplLinuxGlfw.cpp, test/windowTest/proj/cmake/CMakeLists.txt
Based on Petros' #1703 fixing multi-window close bug on Linux.
=> Linux multiwindow close

src/cinder/linux/GstPlayer.cpp
This ensures that the shared context between Cinder and GStreamer is set at the correct point. Relevant especially when using the player in async mode.
=> Use sync handler for need-context message as proposed from upstream gst.

include/cinder/linux/GstPlayer.h, src/cinder/linux/GstPlayer.cpp, test/Video/VideoPlayerScrubTest/proj/cmake/CMakeLists.txt, test/Video/VideoPlayerScrubTest/src/VideoPlayerScrubTestApp.cpp
With these changes we have fluid scrubbing with the GstPlayer. Adds also a raw test app with a dummy slider for testing.
=> GstPlayer: Fix scrub.

src/cinder/gl/Batch.cpp, src/cinder/gl/Context.cpp, src/cinder/gl/Fbo.cpp, src/cinder/gl/Texture.cpp, src/cinder/gl/TransformFeedbackObj.cpp, src/cinder/gl/VaoImplCore.cpp, src/cinder/gl/VaoImplSoftware.cpp, src/cinder/gl/VboMesh.cpp, src/cinder/gl/draw.cpp
=> [warnings] Comment unused parameters in cinder/gl

include/cinder/msw/CinderMsw.h, include/cinder/svg/Svg.h, include/rapidxml/rapidxml_print.hpp, src/AntTweakBar/TwMgr.cpp, src/cinder/CameraUi.cpp, src/cinder/ImageIo.cpp, src/cinder/TriMesh.cpp, src/cinder/gl/GlslProg.cpp, src/cinder/gl/TextureFont.cpp, src/cinder/ip/Blur.cpp, src/cinder/msw/CinderMsw.cpp, src/cinder/qtime/MovieWriter.cpp, src/libtess2/sweep.c, src/libtess2/tess.c, src/r8brain/r8bbase.h, src/videoInput/videoInput.cpp
=> Fix multiple warnings about unused parameters

src/cinder/app/AppBase.cpp
It is defined in cinder.vcxproj.
=> Remove duplicate #define NOMINMAX

docs/htmlsrc/guides/cmake/cmake.html, docs/htmlsrc/guides/index.html
Incorporating Rich's wiki docs into official docs with minor editorial modifications
=> CMake docs

docs/htmlsrc/guides/android-notes/index.html, docs/htmlsrc/guides/linux-notes/index.html, docs/htmlsrc/guides/linux-notes/rpi2.html, docs/htmlsrc/guides/linux-notes/ubuntu.html, docs/htmlsrc/guides/platforms-preproc/index.html, docs/htmlsrc/guides/windows-notes/index.html, docs/htmlsrc/guides/winrt-notes/index.html
Translating and updating wiki pages for inclusion in Cinder docs on Linux, and minor updates to Android and Windows docs.
=> Docs updates

src/cinder/app/linux/AppImplLinuxGlfw.cpp
Should be (mouseX, mouseY) rather than (mouseX, mouseX)
=> Wrong mouse position with onMouseWheel

include/cinder/app/linux/WindowImplLinux.h, src/cinder/app/linux/WindowImplLinuxGlfw.cpp
This allows to launch fullscreen on Linux via `prepareSettings`. Runtime fullscreen toggle remains to be implemented.
=> Implements fullscreen on Linux via prepareSettings.

src/cinder/Path2d.cpp
Pretty sure there is a return missing here
=> Fix Path2d::getSegmentRelativeT when empty

.travis.yml
=> Added Xcode 8.3

src/cinder/Path2d.cpp, test/unit/src/Path2dTest.cpp
Was not dealing properly with closed Path2d case
=> Path2d::getSubPath() fix

proj/cmake/modules/cinderMakeApp.cmake, samples/Earthquake/proj/cmake/CMakeLists.txt, samples/Tubular/proj/cmake/CMakeLists.txt
And fixes an issue when passing in a list of resources to `ci_make_app()`
=> Cmake sample fixes

CONTRIBUTING.md
This came up in https://github.com/cinder/Cinder/pull/1869, seems like something we've all agreed on and do throughout the codebase so I added it.
=> Added guideline about placing else statements on a new line.

src/cinder/app/linux/PlatformLinux.cpp
=> Register tinyexr source / target on linux platform

src/cinder/gl/ShaderPreprocessor.cpp
Minor error handling improvement, this throws the exception at the location where the file path was needed, so we know whether it is an include or root shader file.
=> Report more information when throwing a file not found exception

include/cinder/PolyLine.h
Nothing particularly important, but it came up in a program of mine
=> Add PolyLineT ctor that takes a temporary std::vector

include/cinder/app/linux/AppImplLinux.h, include/cinder/app/linux/WindowImplLinux.h, src/cinder/app/linux/AppImplLinuxEgl.cpp, src/cinder/app/linux/AppImplLinuxGlfw.cpp, src/cinder/app/linux/WindowImplLinuxEgl.cpp, src/cinder/app/linux/WindowImplLinuxGlfw.cpp
This PR updates GLFW implementation to allow for texture / GL resource sharing between windows on Linux.
=> GLFW shared renderer

src/cinder/app/AppBase.cpp
Added the necessary toPixels conversion.
=> Fix copyWindowSurface for HighDensityDisplay

include/cinder/svg/Svg.h, src/cinder/svg/Svg.cpp
A few improvements to SVG parser, including parseFloat() bug fix, letter-spacing attrib on text, a few modifiers, and an iterate() method on Doc/Group
=> SVG improvements

include/cinder/Filesystem.h
See https://github.com/cinder/Cinder/issues/1959
=> [MSVC - FS] Set correct namespace for filesystem on msvc

include/cinder/audio/Node.h, src/cinder/audio/InputNode.cpp, src/cinder/audio/Node.cpp, src/cinder/audio/OutputNode.cpp, src/cinder/audio/Target.cpp, test/_audio/NodeTest/vc2015/NodeTest.vcxproj
* address #1957
* remove `boost::tribool` usage
=> Audio maintenaince

src/cinder/Clipboard.cpp
Allows access the system clipboard now.
=> Fixed linux x11 clipboard problem

include/cinder/audio/msw/ContextWasapi.h, src/cinder/audio/Context.cpp, src/cinder/audio/msw/ContextWasapi.cpp, src/cinder/audio/msw/DeviceManagerWasapi.cpp, src/cinder/audio/msw/FileMediaFoundation.cpp
Addresses issues in #1971. @dsowa-w1 can you try this and see if it works for you?
=> Make ci::audio usable when there is no app on MSW

include/cinder/app/Window.h, src/cinder/app/Window.cpp
Closes #1929, see comments in that issue.
=> added app::Window::getMousePos()

src/cinder/ip/Resize.cpp
See https://github.com/cinder/Cinder/issues/1629
=> [warnigs] Remove unused parameter from Resize.cpp/makeWeightTable

src/cinder/app/linux/RendererGlLinuxHeadless.cpp
=> Fix headless compilation with clang.  

docs/htmlsrc/_assets/js/cinder.js, docs/htmlsrc/guides/flocking/chapter3.html, docs/htmlsrc/guides/flocking/chapter5.html, docs/htmlsrc/guides/gl/fbo/index.html, docs/htmlsrc/guides/index.html, docs/htmlsrc/guides/tour/hello_cinder.html
Search functionality added to Search button on click (#2016)
Fixed broken links in Cinder tour and linked up The Flocking Simulation links properly (#1921)
FBO guide was linked and updated (#1369)
=> Docs bug fixes and guide updates

src/cinder/FileWatcher.cpp, src/cinder/audio/msw/ContextWasapi.cpp
`FileWatcher` and `ci::audio::msw::ContextWasapi`.
=> Name some internal threads

docs/htmlsrc/guides/git/index.html
=> Fix xcode build path in OSX instructions

samples/_timeline/TextInputTween/src/TextInputTweenApp.cpp
The draw loop for dying characters got dropped at some point. Adding it back in for character animOut.
=> fix for character animOut

include/cinder/Camera.h, src/cinder/Camera.cpp
See discussion: https://discourse.libcinder.org/t/why-the-example-of-picking3dapp-does-not-work-together-with-cameraortho
=> Added a `calcRay` implementation for `CameraOrtho`. 

src/cinder/app/linux/WindowImplLinuxGlfw.cpp
Basic additions to handle window decorations in Linux/GLFW.
=> Handling borderless and resizable options in GLFW window creation

src/cinder/Serial.cpp
Came across this while working with DMX controllers.
=> Fix serial device list on Linux.

proj/cmake/libcinder_source_files.cmake
=> Build serial support for non android/ios build.

include/cinder/Buffer.h, src/cinder/Buffer.cpp, test/unit/src/Utilities.cpp
This PR implements a StreamingBuffer class - a double-ended queue that is thread-safe, uses blocks internally for storage, and allows byte-granularity push/pop operations. It's designed for a single-producer, single-consumer model. A good example would be a custom audio decoder running on one thread generating decompressed audio samples to be consumed on another. In fact that is the precise use case it was developed for and we've been using it in production at Rare Volume for about a year. Includes unit tests.
=> StreamingBuffer

include/imgui/imconfig.h, include/imgui/imgui.h, include/imgui/imgui_freetype.h, include/imgui/imgui_impl_opengl3.h, include/imgui/imgui_internal.h, include/imgui/imgui_stdlib.h, include/imgui/imstb_truetype.h, src/imgui/imgui.cpp, src/imgui/imgui_demo.cpp, src/imgui/imgui_draw.cpp, src/imgui/imgui_freetype.cpp, src/imgui/imgui_impl_opengl3.cpp, src/imgui/imgui_stdlib.cpp, src/imgui/imgui_widgets.cpp
Updated via python script + include fix to avoid macro duplication warnings.
=> Dear ImGui v177

include/cinder/app/cocoa/PlatformCocoa.h, proj/xcode/cinder.xcodeproj/project.pbxproj, src/AntTweakBar/TwMgr.cpp, src/cinder/app/Renderer.cpp, src/cinder/app/RendererGl.cpp, src/cinder/app/cocoa/PlatformCocoa.cpp, src/cinder/qtime/QuickTimeImplAvf.mm
- Updated projects to use ARC (automatic reference counting)
- Removed non-ARC constructs
Fixes #2179
=> Fix macOS/iOS builds

docs/htmlsrc/guides/linux-notes/index.html, docs/htmlsrc/guides/linux-notes/ubuntu.html
This PR updates the Ubuntu installation notes and in particular documents some information relevant to build options added previously by @PetrosKataras.
=> Updating Ubuntu notes

include/cinder/app/msw/AppImplMswBasic.h, include/cinder/msw/OutputDebugStringStream.h, include/circular/circular.h, include/tinyexr/tinyexr.h, src/cinder/CaptureImplDirectShow.cpp, src/cinder/ImageTargetFileWic.cpp, src/cinder/app/msw/AppImplMsw.cpp
This should allow Cinder to build with MS' C++20, and removes some warnings from earlier compilers, per #2261.
=> Cpp20 fixes

src/cinder/GeomIo.cpp
This should address #2283 and in a way that minimizes error throughout the circle. Thanks for tackling it @afrancois
=> Circle precision

src/cinder/audio/Param.cpp
Thank you @bradhowes (#2181) and apologies or the delay. I only left out the `continue` statement to keep the code block uniform.
=> fix missing iterator increment

src/cinder/app/msw/PlatformMsw.cpp
Fixes multiple issues in Windows file dialogs:
- getOpenFilePath() and getSaveFilePath() now properly display file type filters and use dynamic buffer allocation
- getFolderPath() no longer passes dangling pointer when setting initial directory
Fixes #1564
=> Fix Windows file dialog bugs

include/cinder/CanvasUi.h, samples/CanvasUi/src/CanvasUiApp.cpp, samples/ImageFileBasic/src/ImageFileBasicApp.cpp, samples/ImageFileBasic/xcode/Info.plist, src/cinder/CanvasUi.cpp
- Added ImGui interface for Open/Save/Fit operations
- Integrated CanvasUi for pan/zoom
- Display image metadata (format, dimensions, color model, etc.)
- Error handling with visual feedback
=> ImageFileBasic: imgui and CanvasUi integration
